// Command genamd64 emits kernels/vek/vek_amd64.s: AVX2 f32 elementwise kernels
// (8-wide YMM). The Go amd64 assembler supports the AVX2 mnemonics directly, so
// no WORD encoding. Each kernel processes a multiple-of-8 element count; the Go
// wrapper in vek_amd64.go handles the <8 tail.
//
//	go run ./kernels/vek/genamd64 > kernels/vek/vek_amd64.s
package main

import (
	"fmt"
	"os"
	"strings"
)

type gen struct{ b strings.Builder }

func (g *gen) w(f string, a ...any) { fmt.Fprintf(&g.b, f+"\n", a...) }

func (g *gen) header() {
	g.w("// Code generated by kernels/vek/genamd64. DO NOT EDIT.")
	g.w("")
	g.w("//go:build amd64")
	g.w("")
	g.w(`#include "textflag.h"`)
	g.w("")
	// constants
	g.w("DATA c_sixth<>+0(SB)/4, $0.16666666666666666")
	g.w("GLOBL c_sixth<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_half<>+0(SB)/4, $0.5")
	g.w("GLOBL c_half<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_one<>+0(SB)/4, $1.0")
	g.w("GLOBL c_one<>(SB), RODATA|NOPTR, $4")
	for _, c := range expConsts {
		if c.sym == "c_one" {
			continue // declared above
		}
		g.w("DATA %s<>+0(SB)/4, $%v", c.sym, c.val)
		g.w("GLOBL %s<>(SB), RODATA|NOPTR, $4", c.sym)
	}
	// min positive normal f32, 8-wide: the sigmoid kernels flush subnormal
	// outputs to zero (sigmoid(x<-87) is subnormal; on x86 a subnormal operand
	// in a downstream multiply costs ~100 cycles — same ambush as softmax).
	for i := 0; i < 32; i += 4 {
		g.w("DATA c_minnorm8<>+%d(SB)/4, $0x00800000", i)
	}
	g.w("GLOBL c_minnorm8<>(SB), RODATA|NOPTR, $32")
	// 8-wide (32-byte) constants used as m256 operands by the erf/gelu kernels
	// (no YMM registers are free while the exp constants are resident).
	for _, c := range erfConsts {
		for i := 0; i < 8; i++ {
			if c.hex != 0 {
				g.w("DATA %s<>+%d(SB)/4, $0x%08x", c.sym, i*4, c.hex)
			} else {
				g.w("DATA %s<>+%d(SB)/4, $%v", c.sym, i*4, c.val)
			}
		}
		g.w("GLOBL %s<>(SB), RODATA|NOPTR, $32", c.sym)
	}
	g.w("")
}

// erfConsts: Abramowitz–Stegun 7.1.26 (|err| ≤ 1.5e-7) plus masks/scales.
var erfConsts = []struct {
	sym string
	val float64
	hex uint32
}{
	{"c_erfp8", 0.3275911, 0}, {"c_erfa1_8", 0.254829592, 0}, {"c_erfa2_8", -0.284496736, 0},
	{"c_erfa3_8", 1.421413741, 0}, {"c_erfa4_8", -1.453152027, 0}, {"c_erfa5_8", 1.061405429, 0},
	{"c_abs8", 0, 0x7fffffff}, {"c_sign8", 0, 0x80000000},
	{"c_invsqrt2_8", 0.70710678118654752, 0}, {"c_half8", 0.5, 0},
}

// erfBody: Y0 ← erf(Y0); scale is the factor applied to x (1 for erf, 1/√2 for
// gelu). Clobbers Y1..Y3. The input is re-read from (SI) for |x| and the sign
// because expBody needs all three scratch registers.
func erfBody(g *gen, scaled bool) {
	g.w("\tVANDPS c_abs8<>(SB), Y0, Y1     // |x|")
	g.w("\tVMULPS Y1, Y1, Y0              // x^2")
	g.w("\tVXORPS c_sign8<>(SB), Y0, Y0    // -x^2")
	expBody(g)
	g.w("\tVMOVUPS (SI), Y1")
	if scaled {
		g.w("\tVMULPS c_invsqrt2_8<>(SB), Y1, Y1")
	}
	g.w("\tVANDPS c_abs8<>(SB), Y1, Y1     // |x| again")
	g.w("\tVMOVUPS Y15, Y2                // 1")
	g.w("\tVFMADD231PS c_erfp8<>(SB), Y1, Y2 // 1 + p|x|")
	g.w("\tVDIVPS Y2, Y15, Y2             // t")
	g.w("\tVMOVUPS c_erfa5_8<>(SB), Y3")
	g.w("\tVFMADD213PS c_erfa4_8<>(SB), Y2, Y3 // a5 t + a4")
	g.w("\tVFMADD213PS c_erfa3_8<>(SB), Y2, Y3")
	g.w("\tVFMADD213PS c_erfa2_8<>(SB), Y2, Y3")
	g.w("\tVFMADD213PS c_erfa1_8<>(SB), Y2, Y3")
	g.w("\tVMULPS Y2, Y3, Y3              // t*poly")
	g.w("\tVMULPS Y3, Y0, Y0              // *e^{-x^2}")
	g.w("\tVSUBPS Y0, Y15, Y0             // 1 - ...")
	g.w("\tVMOVUPS (SI), Y1")
	g.w("\tVANDPS c_sign8<>(SB), Y1, Y1    // sign(x)")
	g.w("\tVORPS Y1, Y0, Y0")
}

// Exp constants (Cephes expf): x clamped to [lo,hi]; n = round(x·log2e);
// r = x − n·ln2 (hi/lo split); e^r ≈ 1 + r + r²·P(r); result = 2^n·e^r by
// adding n<<23 to the float bits. Below lo saturates at the smallest normal,
// above hi at ~2.3e38. Registers Y4..Y15 hold the constants, Y1..Y3 scratch.
var expConsts = []struct {
	reg int
	sym string
	val float64
}{
	{4, "c_explo", -87.33654}, {5, "c_exphi", 88.37626}, {6, "c_log2e", 1.44269504088896341},
	{7, "c_ln2hi", 0.693359375}, {8, "c_ln2lo", -2.12194440e-4},
	{9, "c_p0", 1.9875691500e-4}, {10, "c_p1", 1.3981999507e-3}, {11, "c_p2", 8.3334519073e-3},
	{12, "c_p3", 4.1665795894e-2}, {13, "c_p4", 1.6666665459e-1}, {14, "c_p5", 5.0000001201e-1},
	{15, "c_one", 1.0},
}

func expPrep(g *gen) {
	for _, c := range expConsts {
		g.w("\tVBROADCASTSS %s<>(SB), Y%d", c.sym, c.reg)
	}
}

// expBody: Y0 ← exp(Y0); clobbers Y1..Y3.
func expBody(g *gen) {
	g.w("\tVMAXPS Y4, Y0, Y0          // clamp lo")
	g.w("\tVMINPS Y5, Y0, Y0          // clamp hi")
	g.w("\tVMULPS Y6, Y0, Y1          // x*log2e")
	g.w("\tVROUNDPS $0, Y1, Y1        // n = round-to-nearest")
	g.w("\tVFNMADD231PS Y7, Y1, Y0    // r = x - n*ln2hi")
	g.w("\tVFNMADD231PS Y8, Y1, Y0    // r -= n*ln2lo")
	g.w("\tVMOVUPS Y10, Y2            // p1")
	g.w("\tVFMADD231PS Y9, Y0, Y2     // p0*r + p1")
	g.w("\tVMOVUPS Y11, Y3            // p2")
	g.w("\tVFMADD231PS Y2, Y0, Y3")
	g.w("\tVMOVUPS Y12, Y2            // p3")
	g.w("\tVFMADD231PS Y3, Y0, Y2")
	g.w("\tVMOVUPS Y13, Y3            // p4")
	g.w("\tVFMADD231PS Y2, Y0, Y3")
	g.w("\tVMOVUPS Y14, Y2            // p5")
	g.w("\tVFMADD231PS Y3, Y0, Y2     // P(r)")
	g.w("\tVMULPS Y0, Y0, Y3          // r^2")
	g.w("\tVADDPS Y15, Y0, Y0         // r+1")
	g.w("\tVFMADD231PS Y3, Y2, Y0     // += P*r^2")
	g.w("\tVCVTPS2DQ Y1, Y1           // n → int")
	g.w("\tVPSLLD $23, Y1, Y1")
	g.w("\tVPADDD Y1, Y0, Y0          // * 2^n")
}

// binary: func name_asm(dst, a, b []float32, n int); n multiple of 8.
func (g *gen) binary(name, mnem string) {
	g.w("// func %s_asm(dst, a, b []float32, n int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-80", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ a_base+24(FP), SI")
	g.w("\tMOVQ b_base+48(FP), BX")
	g.w("\tMOVQ n+72(FP), CX")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	g.w("\t%s (BX), Y0, Y0", mnem)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, BX")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// unary: func name_asm(dst, src []float32, n int, <args>). prep sets up constant
// YMM regs; body transforms Y0 (input->output) using scratch Y1 and consts.
func (g *gen) unary(name string, frame int, prep func(*gen), body func(*gen)) {
	g.w("// func %s_asm(dst, src []float32, n int, ...)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-%d", name, frame)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	if prep != nil {
		prep(g)
	}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	body(g)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

func main() {
	g := &gen{}
	g.header()

	g.binary("add", "VADDPS")
	g.binary("sub", "VSUBPS")
	g.binary("mul", "VMULPS")
	g.binary("div", "VDIVPS")
	g.binary("maxpair", "VMAXPS")
	g.binary("minpair", "VMINPS")

	// relu: Y0 = max(Y0, 0)
	g.unary("relu", 56, func(g *gen) { g.w("\tVXORPS Y15, Y15, Y15") }, func(g *gen) {
		g.w("\tVMAXPS Y15, Y0, Y0")
	})

	// hardswish: t = clamp(x/6+0.5,0,1); out = x*t
	prepHS := func(g *gen) {
		g.w("\tVBROADCASTSS c_sixth<>(SB), Y13")
		g.w("\tVBROADCASTSS c_half<>(SB), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardswish", 56, prepHS, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1        // t = 0.5")
		g.w("\tVFMADD231PS Y13, Y0, Y1 // t += (1/6)*x")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMULPS Y1, Y0, Y0      // out = x*t")
	})

	// hardsigmoid(alpha,beta): clamp(alpha*x+beta,0,1)
	prepHSig := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVBROADCASTSS beta+60(FP), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardsigmoid", 64, prepHSig, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1")
		g.w("\tVFMADD231PS Y13, Y0, Y1")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMOVUPS Y1, Y0")
	})

	// clip(lo,hi)
	prepClip := func(g *gen) {
		g.w("\tVBROADCASTSS lo+56(FP), Y14")
		g.w("\tVBROADCASTSS hi+60(FP), Y15")
	}
	g.unary("clip", 64, prepClip, func(g *gen) {
		g.w("\tVMAXPS Y14, Y0, Y0")
		g.w("\tVMINPS Y15, Y0, Y0")
	})

	// leakyrelu(alpha): max(x,0) + alpha*min(x,0)
	prepLeaky := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("leakyrelu", 60, prepLeaky, func(g *gen) {
		g.w("\tVMINPS Y15, Y0, Y1     // neg part")
		g.w("\tVMAXPS Y15, Y0, Y0     // pos part")
		g.w("\tVFMADD231PS Y13, Y1, Y0 // out = pos + alpha*neg")
	})

	prepScalar := func(g *gen) { g.w("\tVBROADCASTSS s+56(FP), Y13") }
	g.unary("addscalar", 60, prepScalar, func(g *gen) { g.w("\tVADDPS Y13, Y0, Y0") })
	g.unary("mulscalar", 60, prepScalar, func(g *gen) { g.w("\tVMULPS Y13, Y0, Y0") })

	g.unary("exp", 56, expPrep, expBody)
	g.unary("silu", 56, expPrep, func(g *gen) {
		// expBody clobbers Y1..Y3, so x is re-read from the source pointer
		// after the sigmoid (SI still points at this vector; dst may alias src
		// but the store happens after this body).
		g.w("\tVXORPS Y1, Y1, Y1")
		g.w("\tVSUBPS Y0, Y1, Y0          // -x")
		expBody(g)
		g.w("\tVADDPS Y15, Y0, Y0         // 1+e^-x")
		g.w("\tVDIVPS Y0, Y15, Y0         // sigmoid")
		g.w("\tVCMPPS $0x1d, c_minnorm8<>(SB), Y0, Y1 // >= FLT_MIN?")
		g.w("\tVANDPS Y1, Y0, Y0          // flush subnormal sigmoid to 0")
		g.w("\tVMULPS (SI), Y0, Y0        // * x (reload from source)")
	})
	g.unary("sigmoid", 56, expPrep, func(g *gen) {
		g.w("\tVXORPS Y1, Y1, Y1")
		g.w("\tVSUBPS Y0, Y1, Y0          // -x")
		expBody(g)
		g.w("\tVADDPS Y15, Y0, Y0         // 1+e^-x")
		g.w("\tVDIVPS Y0, Y15, Y0         // 1/(1+e^-x)")
		g.w("\tVCMPPS $0x1d, c_minnorm8<>(SB), Y0, Y1 // >= FLT_MIN?")
		g.w("\tVANDPS Y1, Y0, Y0          // flush subnormal sigmoid to 0")
	})

	g.axpy()
	g.quantConsts()
	g.requant("requantu8", true)
	g.requant("requanti8", false)
	g.quant("quantu8", true)
	g.quant("quanti8", false)
	g.dequant("dequantu8", true)
	g.dequant("dequanti8", false)
	g.shift()
	g.widen()
	g.deint16()
	g.qlut()
	g.dotbf16()
	g.axpybf16()
	for _, ks := range [][2]int{{3, 1}, {3, 2}, {5, 1}, {5, 2}} {
		g.dwblkgen(ks[0], ks[1])
	}
	g.pwblk()
	for _, k := range [][2]int{{3, 3}, {5, 5}, {3, 2}, {3, 1}, {5, 3}, {5, 2}} {
		g.qdw(k[0], k[1])
	}
	for _, k := range dwShapes {
		g.dwconv(k[0], k[1])
	}
	g.dot()

	g.unary("erf", 56, expPrep, func(g *gen) { erfBody(g, false) })
	g.unary("gelu", 56, expPrep, func(g *gen) {
		g.w("\tVMULPS c_invsqrt2_8<>(SB), Y0, Y0 // x/sqrt2")
		erfBody(g, true)
		g.w("\tVADDPS Y15, Y0, Y0             // 1+erf")
		g.w("\tVMULPS (SI), Y0, Y0            // *x")
		g.w("\tVMULPS c_half8<>(SB), Y0, Y0    // *0.5")
	})

	os.Stdout.WriteString(g.b.String())
}

// axpy: dst += a*src.
func (g *gen) axpy() {
	g.w("// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src")
	g.w("TEXT ·axpy_asm(SB), NOSPLIT, $0-60")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS a+56(FP), Y13")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0")
	g.w("\tVMOVUPS (SI), Y1")
	g.w("\tVFMADD231PS Y13, Y1, Y0")
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwconv: one interior row of a stride-1 KxK depthwise conv, adding into dst.
// dst += sum_{kh,kw} wpacked[kh*K+kw] * src[kh*W + col + kw]. 8 cols/iter.
func (g *gen) dwconv(KH, KW int) {
	name := fmt.Sprintf("dwconv%dx%ds1", KH, KW)
	g.w("// func %s_asm(dst, src []float32, wpacked []float32, ncols, W int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-88", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ wpacked_base+48(FP), BX")
	g.w("\tMOVQ ncols+72(FP), CX")
	g.w("\tMOVQ W+80(FP), DX")
	g.w("\tSHLQ $2, DX // W in bytes")
	rows := []string{"R8", "R9", "R10", "R11", "R12"}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0 // acc = dst[c..c+8]")
	// set up row pointers R8..R(8+KH-1) = SI + kh*DX
	g.w("\tMOVQ SI, %s", rows[0])
	for kh := 1; kh < KH; kh++ {
		g.w("\tLEAQ (%s)(DX*1), %s", rows[kh-1], rows[kh])
	}
	for kh := 0; kh < KH; kh++ {
		for kw := 0; kw < KW; kw++ {
			t := kh*KW + kw
			g.w("\tVBROADCASTSS %d(BX), Y1", t*4)
			g.w("\tVMOVUPS %d(%s), Y2", kw*4, rows[kh])
			g.w("\tVFMADD231PS Y1, Y2, Y0")
		}
	}
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, DI")
	g.w("\tADDQ $32, SI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwShapes are the (KH, KW) depthwise row kernels generated (see ../gen).
var dwShapes = [][2]int{{3, 3}, {5, 5}, {3, 2}, {3, 1}, {5, 3}, {5, 2}}

// dot emits func dot_asm(a, b []float32, n int, out []float32): out[0:32] =
// 32 partial sums (4 YMM accumulators × 8 lanes); the Go wrapper adds them.
// n is a multiple of 32.
func (g *gen) dot() {
	g.w("// func dot_asm(a, b []float32, n int, out []float32)")
	g.w("TEXT ·dot_asm(SB), NOSPLIT, $0-80")
	g.w("\tMOVQ a_base+0(FP), SI")
	g.w("\tMOVQ b_base+24(FP), BX")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tMOVQ out_base+56(FP), DI")
	for i := 0; i < 4; i++ {
		g.w("\tVXORPS Y%d, Y%d, Y%d", i, i, i)
	}
	g.w("loop:")
	g.w("\tCMPQ CX, $32")
	g.w("\tJL done")
	for i := 0; i < 4; i++ {
		g.w("\tVMOVUPS %d(SI), Y%d", i*32, 4+i)
		g.w("\tVFMADD231PS %d(BX), Y%d, Y%d", i*32, 4+i, i)
	}
	g.w("\tADDQ $128, SI")
	g.w("\tADDQ $128, BX")
	g.w("\tSUBQ $32, CX")
	g.w("\tJMP loop")
	g.w("done:")
	for i := 0; i < 4; i++ {
		g.w("\tVMOVUPS Y%d, %d(DI)", i, i*32)
	}
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// quantConsts emits the 32-byte constants used by the quant kernels.
func (g *gen) quantConsts() {
	c32 := func(sym string, bytes []byte) {
		for i := 0; i < 32; i += 8 {
			var v uint64
			for j := 7; j >= 0; j-- {
				v = v<<8 | uint64(bytes[i+j])
			}
			g.w("DATA %s<>+%d(SB)/8, $0x%016x", sym, i, v)
		}
		g.w("GLOBL %s<>(SB), RODATA|NOPTR, $32", sym)
	}
	rep := func(b byte) []byte {
		out := make([]byte, 32)
		for i := range out {
			out[i] = b
		}
		return out
	}
	c32("q_x80", rep(0x80))
	c32("q_x0f", rep(0x0f))
	// per-128-lane even/odd i16 gather: bytes [0 1 4 5 8 9 12 13 | 2 3 6 7 10 11 14 15]
	lane := []byte{0, 1, 4, 5, 8, 9, 12, 13, 2, 3, 6, 7, 10, 11, 14, 15}
	c32("q_deint", append(append([]byte{}, lane...), lane...))
}

// requant: dst = sat(round_even(f32(src+corr)*mult + off)) for u8 / i8.
func (g *gen) requant(name string, unsigned bool) {
	g.w("// func %s_asm(dst []%s, src []int32, n int, mult, off float32, corr int32)", name, map[bool]string{true: "uint8", false: "int8"}[unsigned])
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-68", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS mult+56(FP), Y11")
	g.w("\tVBROADCASTSS off+60(FP), Y12")
	g.w("\tMOVL corr+64(FP), AX")
	g.w("\tMOVL AX, X13")
	g.w("\tVPBROADCASTD X13, Y13")
	if unsigned {
		g.w("\tVXORPS Y14, Y14, Y14            // lo clamp 0")
		g.w("\tMOVL $0x437f0000, AX            // 255.0")
	} else {
		g.w("\tMOVL $0xc3000000, AX            // -128.0")
		g.w("\tMOVL AX, X14")
		g.w("\tVBROADCASTSS X14, Y14")
		g.w("\tMOVL $0x42fe0000, AX            // 127.0")
	}
	g.w("\tMOVL AX, X15")
	g.w("\tVBROADCASTSS X15, Y15")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	g.w("\tVMOVDQU (SI), Y0")
	g.w("\tVMOVDQU 32(SI), Y1")
	g.w("\tVPADDD Y13, Y0, Y0")
	g.w("\tVPADDD Y13, Y1, Y1")
	g.w("\tVCVTDQ2PS Y0, Y0")
	g.w("\tVCVTDQ2PS Y1, Y1")
	g.w("\tVMULPS Y11, Y0, Y0")
	g.w("\tVMULPS Y11, Y1, Y1")
	g.w("\tVADDPS Y12, Y0, Y0")
	g.w("\tVADDPS Y12, Y1, Y1")
	g.w("\tVMAXPS Y14, Y0, Y0")
	g.w("\tVMAXPS Y14, Y1, Y1")
	g.w("\tVMINPS Y15, Y0, Y0")
	g.w("\tVMINPS Y15, Y1, Y1")
	g.w("\tVCVTPS2DQ Y0, Y0                // round-to-nearest-even (MXCSR default)")
	g.w("\tVCVTPS2DQ Y1, Y1")
	g.w("\tVPACKSSDW Y1, Y0, Y0")
	g.w("\tVPERMQ $0xd8, Y0, Y0")
	g.w("\tVEXTRACTI128 $1, Y0, X1")
	if unsigned {
		g.w("\tVPACKUSWB X1, X0, X0")
	} else {
		g.w("\tVPACKSSWB X1, X0, X0")
	}
	g.w("\tVMOVDQU X0, (DI)")
	g.w("\tADDQ $64, SI")
	g.w("\tADDQ $16, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// quant: dst = sat(round_even(src/scale + zp)) for u8 / i8, src f32.
func (g *gen) quant(name string, unsigned bool) {
	g.w("// func %s_asm(dst []%s, src []float32, n int, scale, zp float32)", name, map[bool]string{true: "uint8", false: "int8"}[unsigned])
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-64", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS scale+56(FP), Y11")
	g.w("\tVBROADCASTSS zp+60(FP), Y12")
	if unsigned {
		g.w("\tVXORPS Y14, Y14, Y14")
		g.w("\tMOVL $0x437f0000, AX            // 255.0")
	} else {
		g.w("\tMOVL $0xc3000000, AX            // -128.0")
		g.w("\tMOVL AX, X14")
		g.w("\tVBROADCASTSS X14, Y14")
		g.w("\tMOVL $0x42fe0000, AX            // 127.0")
	}
	g.w("\tMOVL AX, X15")
	g.w("\tVBROADCASTSS X15, Y15")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	g.w("\tVMOVUPS 32(SI), Y1")
	g.w("\tVDIVPS Y11, Y0, Y0")
	g.w("\tVDIVPS Y11, Y1, Y1")
	g.w("\tVADDPS Y12, Y0, Y0")
	g.w("\tVADDPS Y12, Y1, Y1")
	g.w("\tVMAXPS Y14, Y0, Y0")
	g.w("\tVMAXPS Y14, Y1, Y1")
	g.w("\tVMINPS Y15, Y0, Y0")
	g.w("\tVMINPS Y15, Y1, Y1")
	g.w("\tVCVTPS2DQ Y0, Y0")
	g.w("\tVCVTPS2DQ Y1, Y1")
	g.w("\tVPACKSSDW Y1, Y0, Y0")
	g.w("\tVPERMQ $0xd8, Y0, Y0")
	g.w("\tVEXTRACTI128 $1, Y0, X1")
	if unsigned {
		g.w("\tVPACKUSWB X1, X0, X0")
	} else {
		g.w("\tVPACKSSWB X1, X0, X0")
	}
	g.w("\tVMOVDQU X0, (DI)")
	g.w("\tADDQ $64, SI")
	g.w("\tADDQ $16, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dequant: dst = f32(src - zp) * scale for u8 / i8 sources.
func (g *gen) dequant(name string, unsigned bool) {
	g.w("// func %s_asm(dst []float32, src []%s, n int, scale float32, zp int32)", name, map[bool]string{true: "uint8", false: "int8"}[unsigned])
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-64", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS scale+56(FP), Y11")
	g.w("\tMOVL zp+60(FP), AX")
	g.w("\tMOVL AX, X12")
	g.w("\tVPBROADCASTD X12, Y12")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	if unsigned {
		g.w("\tVPMOVZXBD (SI), Y0")
		g.w("\tVPMOVZXBD 8(SI), Y1")
	} else {
		g.w("\tVPMOVSXBD (SI), Y0")
		g.w("\tVPMOVSXBD 8(SI), Y1")
	}
	g.w("\tVPSUBD Y12, Y0, Y0")
	g.w("\tVPSUBD Y12, Y1, Y1")
	g.w("\tVCVTDQ2PS Y0, Y0")
	g.w("\tVCVTDQ2PS Y1, Y1")
	g.w("\tVMULPS Y11, Y0, Y0")
	g.w("\tVMULPS Y11, Y1, Y1")
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tVMOVUPS Y1, 32(DI)")
	g.w("\tADDQ $16, SI")
	g.w("\tADDQ $64, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// shiftu8s8: dst = src ^ 0x80 (u8 -> s8 shift), 64-byte blocks.
func (g *gen) shift() {
	g.w("// func shiftu8s8_asm(dst []int8, src []uint8, n int)")
	g.w("TEXT ·shiftu8s8_asm(SB), NOSPLIT, $0-56")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVMOVDQU q_x80<>(SB), Y15")
	g.w("loop:")
	g.w("\tCMPQ CX, $64")
	g.w("\tJL done")
	g.w("\tVPXOR (SI), Y15, Y0")
	g.w("\tVPXOR 32(SI), Y15, Y1")
	g.w("\tVMOVDQU Y0, (DI)")
	g.w("\tVMOVDQU Y1, 32(DI)")
	g.w("\tADDQ $64, SI")
	g.w("\tADDQ $64, DI")
	g.w("\tSUBQ $64, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// widens8: dst(i16) = src(s8), 16 per iteration.
func (g *gen) widen() {
	g.w("// func widens8_asm(dst []int16, src []int8, n int)")
	g.w("TEXT ·widens8_asm(SB), NOSPLIT, $0-56")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	g.w("\tVPMOVSXBW (SI), Y0")
	g.w("\tVMOVDQU Y0, (DI)")
	g.w("\tADDQ $16, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// deint16: ev[i]=src[2i], od[i]=src[2i+1], 8 pairs per iteration.
func (g *gen) deint16() {
	g.w("// func deint16_asm(ev, od []int16, src []int16, n int)")
	g.w("TEXT ·deint16_asm(SB), NOSPLIT, $0-80")
	g.w("\tMOVQ ev_base+0(FP), DI")
	g.w("\tMOVQ od_base+24(FP), BX")
	g.w("\tMOVQ src_base+48(FP), SI")
	g.w("\tMOVQ n+72(FP), CX")
	g.w("\tVMOVDQU q_deint<>(SB), Y15")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVDQU (SI), Y0                // 8 (ev,od) pairs")
	g.w("\tVPSHUFB Y15, Y0, Y0             // per lane: ev0-3 | od0-3")
	g.w("\tVPERMQ $0xd8, Y0, Y0            // ev0-7 | od0-7")
	g.w("\tVEXTRACTI128 $1, Y0, X1")
	g.w("\tVMOVDQU X0, (DI)")
	g.w("\tVMOVDQU X1, (BX)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $16, DI")
	g.w("\tADDQ $16, BX")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// qlut: 256-entry byte LUT via the AVX2 nibble trick — 16 VPSHUFB rounds,
// one per 16-entry table chunk, selected by comparing high nibbles.
func (g *gen) qlut() {
	g.w("// func qlut_asm(dst *uint8, src *uint8, n int64, tab *uint8)")
	g.w("TEXT ·qlut_asm(SB), NOSPLIT, $0-32")
	g.w("\tMOVQ dst+0(FP), DI")
	g.w("\tMOVQ src+8(FP), SI")
	g.w("\tMOVQ n+16(FP), CX")
	g.w("\tMOVQ tab+24(FP), DX")
	g.w("\tVMOVDQU q_x0f<>(SB), Y14")
	g.w("loop:")
	g.w("\tCMPQ CX, $32")
	g.w("\tJL done")
	g.w("\tVMOVDQU (SI), Y0")
	g.w("\tVPAND Y14, Y0, Y1               // lo nibbles")
	g.w("\tVPSRLW $4, Y0, Y2")
	g.w("\tVPAND Y14, Y2, Y2               // hi nibbles")
	g.w("\tVPXOR Y3, Y3, Y3                // acc")
	g.w("\tVPXOR Y4, Y4, Y4                // chunk index j (bytes)")
	g.w("\tVPCMPEQB Y5, Y5, Y5             // all-ones (-1 bytes)")
	g.w("\tMOVQ DX, AX")
	g.w("\tMOVQ $16, R8")
	g.w("chunk:")
	g.w("\tVBROADCASTI128 (AX), Y6         // table chunk j")
	g.w("\tVPCMPEQB Y4, Y2, Y7             // hi == j?")
	g.w("\tVPSHUFB Y1, Y6, Y6              // chunk[lo]")
	g.w("\tVPAND Y7, Y6, Y6")
	g.w("\tVPOR Y6, Y3, Y3")
	g.w("\tVPSUBB Y5, Y4, Y4               // j++")
	g.w("\tADDQ $16, AX")
	g.w("\tDECQ R8")
	g.w("\tJNZ chunk")
	g.w("\tVMOVDQU Y3, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $32, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// qdw emits a stride-1 KHxKW int8-depthwise row kernel:
// acc[c] += sum_{kh,kw} wp[kh*KW+kw] * src[kh*W + c + kw]  (s16 in, s32 acc).
// Weights preload into YMM registers when they fit (taps <= 9); larger
// kernels broadcast each tap from memory inside the loop.
func (g *gen) qdw(KH, KW int) {
	name := fmt.Sprintf("qdw%dx%ds1", KH, KW)
	taps := KH * KW
	preload := taps <= 9
	g.w("// func %s_asm(acc []int32, src, wp []int16, ncols, W int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-88", name)
	g.w("\tMOVQ acc_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ wp_base+48(FP), BX")
	g.w("\tMOVQ ncols+72(FP), CX")
	g.w("\tMOVQ W+80(FP), AX")
	rows := []string{"SI", "R9", "R10", "R11", "R12"}
	for kh := 1; kh < KH; kh++ {
		g.w("\tLEAQ (%s)(AX*2), %s", rows[kh-1], rows[kh])
	}
	if preload {
		for t := 0; t < taps; t++ {
			r := 15 - t
			g.w("\tVPBROADCASTW %d(BX), X%d", 2*t, r)
			g.w("\tVPMOVSXWD X%d, Y%d", r, r)
		}
	}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVDQU (DI), Y0")
	for kh := 0; kh < KH; kh++ {
		for kw := 0; kw < KW; kw++ {
			t := kh*KW + kw
			g.w("\tVPMOVSXWD %d(%s), Y1", 2*kw, rows[kh])
			if preload {
				g.w("\tVPMULLD Y%d, Y1, Y1", 15-t)
			} else {
				g.w("\tVPBROADCASTW %d(BX), X2", 2*t)
				g.w("\tVPMOVSXWD X2, Y2")
				g.w("\tVPMULLD Y2, Y1, Y1")
			}
			g.w("\tVPADDD Y1, Y0, Y0")
		}
	}
	g.w("\tVMOVDQU Y0, (DI)")
	for kh := 0; kh < KH; kh++ {
		g.w("\tADDQ $16, %s", rows[kh])
	}
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dotbf16: Σ a[i]·widen(b[i]) — f32 a, bf16 b (bits<<16), 16 per iteration.
func (g *gen) dotbf16() {
	g.w("// func dotbf16_asm(a []float32, b []uint16, n int) float32")
	g.w("TEXT ·dotbf16_asm(SB), NOSPLIT, $0-60")
	g.w("\tMOVQ a_base+0(FP), DI")
	g.w("\tMOVQ b_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVXORPS Y0, Y0, Y0")
	g.w("\tVXORPS Y1, Y1, Y1")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	g.w("\tVPMOVZXWD (SI), Y2")
	g.w("\tVPMOVZXWD 16(SI), Y3")
	g.w("\tVPSLLD $16, Y2, Y2")
	g.w("\tVPSLLD $16, Y3, Y3")
	g.w("\tVFMADD231PS (DI), Y2, Y0")
	g.w("\tVFMADD231PS 32(DI), Y3, Y1")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $64, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVADDPS Y1, Y0, Y0")
	g.w("\tVEXTRACTF128 $1, Y0, X1")
	g.w("\tVADDPS X1, X0, X0")
	g.w("\tVHADDPS X0, X0, X0")
	g.w("\tVHADDPS X0, X0, X0")
	g.w("\tVMOVSS X0, ret+56(FP)")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// axpybf16: dst += a·widen(src) — f32 dst, bf16 src, 16 per iteration.
func (g *gen) axpybf16() {
	g.w("// func axpybf16_asm(dst []float32, src []uint16, n int, a float32)")
	g.w("TEXT ·axpybf16_asm(SB), NOSPLIT, $0-60")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS a+56(FP), Y13")
	g.w("loop:")
	g.w("\tCMPQ CX, $16")
	g.w("\tJL done")
	g.w("\tVPMOVZXWD (SI), Y2")
	g.w("\tVPMOVZXWD 16(SI), Y3")
	g.w("\tVPSLLD $16, Y2, Y2")
	g.w("\tVPSLLD $16, Y3, Y3")
	g.w("\tVMOVUPS (DI), Y0")
	g.w("\tVMOVUPS 32(DI), Y1")
	g.w("\tVFMADD231PS Y13, Y2, Y0")
	g.w("\tVFMADD231PS Y13, Y3, Y1")
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tVMOVUPS Y1, 32(DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $64, DI")
	g.w("\tSUBQ $16, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwblkgen emits one output row of a KxK stride-S depthwise conv in
// channel-blocked layout ([.][8] f32, spatially pre-padded src). 3x3 keeps
// its 9 tap vectors in registers; 5x5's 25 stream from L1 (w operand reads
// fold into the FMAs). Stride 2 advances the source two blocks per output.
func (g *gen) dwblkgen(K, S int) {
	name := fmt.Sprintf("dwblk8k%ds%d", K, S)
	rows := []string{"SI", "DX", "R8", "R9", "R10"}[:K]
	g.w("// func %s_asm(dst, src, w []float32, ncols, wp int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-88", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ w_base+48(FP), BX")
	g.w("\tMOVQ ncols+72(FP), CX")
	g.w("\tMOVQ wp+80(FP), AX")
	g.w("\tSHLQ $5, AX // row stride in bytes (wp*8*4)")
	for r := 1; r < K; r++ {
		if r == 1 {
			g.w("\tLEAQ (SI)(AX*1), %s", rows[1])
		} else {
			g.w("\tLEAQ (%s)(AX*1), %s", rows[r-1], rows[r])
		}
	}
	inRegs := K == 3
	if inRegs {
		for t := 0; t < 9; t++ {
			g.w("\tVMOVUPS %d(BX), Y%d", t*32, 7+t)
		}
	}
	g.w("%s_loop:", name)
	g.w("\tTESTQ CX, CX")
	g.w("\tJE %s_done", name)
	first := true
	for kh := 0; kh < K; kh++ {
		for kw := 0; kw < K; kw++ {
			t := kh*K + kw
			var wop string
			if inRegs {
				wop = fmt.Sprintf("Y%d", 7+t)
			} else {
				g.w("\tVMOVUPS %d(BX), Y2", t*32)
				wop = "Y2"
			}
			if first {
				g.w("\tVMULPS %d(%s), %s, Y0", kw*32, rows[kh], wop)
				first = false
			} else {
				g.w("\tVFMADD231PS %d(%s), %s, Y0", kw*32, rows[kh], wop)
			}
		}
	}
	g.w("\tVMOVUPS Y0, (DI)")
	step := 32 * S
	for _, r := range rows {
		g.w("\tADDQ $%d, %s", step, r)
	}
	g.w("\tADDQ $32, DI")
	g.w("\tDECQ CX")
	g.w("\tJMP %s_loop", name)
	g.w("%s_done:", name)
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// pwblk: channel-blocked 1x1 conv micro-kernel — 6 spatial positions x 16
// output channels (two 8-blocks). x is nChw8c [cb][P][8]; weights packed
// [ci over Cin][16] for this output pair. Per input channel: 2 weight loads
// + 6 broadcasts feed 12 FMAs (the paired-panel load ratio, applied from
// day one).
func (g *gen) pwblk() {
	g.w("// func pwblk6x16_asm(dst0, dst1, x, w []float32, cin, xbstride int)")
	g.w("// dst0/dst1: 6 positions x 8 each; x: base at position 0 of block 0;")
	g.w("// xbstride: bytes between input channel blocks; w: [cin][16].")
	g.w("TEXT ·pwblk6x16_asm(SB), NOSPLIT, $0-112")
	g.w("\tMOVQ dst0_base+0(FP), DI")
	g.w("\tMOVQ dst1_base+24(FP), SI")
	g.w("\tMOVQ x_base+48(FP), DX")
	g.w("\tMOVQ w_base+72(FP), BX")
	g.w("\tMOVQ cin+96(FP), CX")
	g.w("\tMOVQ xbstride+104(FP), R10")
	for r := 0; r < 12; r++ {
		g.w("\tVXORPS Y%d, Y%d, Y%d", r, r, r)
	}
	g.w("\tMOVQ DX, R8  // current block base")
	g.w("\tXORQ R9, R9  // ci within block")
	g.w("pwloop:")
	g.w("\tTESTQ CX, CX")
	g.w("\tJE pwdone")
	g.w("\tVMOVUPS (BX), Y12")
	g.w("\tVMOVUPS 32(BX), Y13")
	g.w("\tADDQ $64, BX")
	g.w("\tLEAQ (R8)(R9*4), R11 // &x[block][0][ci]")
	for p := 0; p < 6; p++ {
		g.w("\tVBROADCASTSS %d(R11), Y14", p*32)
		g.w("\tVFMADD231PS Y14, Y12, Y%d", 2*p)
		g.w("\tVFMADD231PS Y14, Y13, Y%d", 2*p+1)
	}
	g.w("\tINCQ R9")
	g.w("\tCMPQ R9, $8")
	g.w("\tJL pwnext")
	g.w("\tXORQ R9, R9")
	g.w("\tADDQ R10, R8")
	g.w("pwnext:")
	g.w("\tDECQ CX")
	g.w("\tJMP pwloop")
	g.w("pwdone:")
	for p := 0; p < 6; p++ {
		g.w("\tVMOVUPS Y%d, %d(DI)", 2*p, p*32)
		g.w("\tVMOVUPS Y%d, %d(SI)", 2*p+1, p*32)
	}
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}
