// Command genamd64 emits kernels/vek/vek_amd64.s: AVX2 f32 elementwise kernels
// (8-wide YMM). The Go amd64 assembler supports the AVX2 mnemonics directly, so
// no WORD encoding. Each kernel processes a multiple-of-8 element count; the Go
// wrapper in vek_amd64.go handles the <8 tail.
//
//	go run ./kernels/vek/genamd64 > kernels/vek/vek_amd64.s
package main

import (
	"fmt"
	"os"
	"strings"
)

type gen struct{ b strings.Builder }

func (g *gen) w(f string, a ...any) { fmt.Fprintf(&g.b, f+"\n", a...) }

func (g *gen) header() {
	g.w("// Code generated by kernels/vek/genamd64. DO NOT EDIT.")
	g.w("")
	g.w("//go:build amd64")
	g.w("")
	g.w(`#include "textflag.h"`)
	g.w("")
	// constants
	g.w("DATA c_sixth<>+0(SB)/4, $0.16666666666666666")
	g.w("GLOBL c_sixth<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_half<>+0(SB)/4, $0.5")
	g.w("GLOBL c_half<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_one<>+0(SB)/4, $1.0")
	g.w("GLOBL c_one<>(SB), RODATA|NOPTR, $4")
	g.w("")
}

// binary: func name_asm(dst, a, b []float32, n int); n multiple of 8.
func (g *gen) binary(name, mnem string) {
	g.w("// func %s_asm(dst, a, b []float32, n int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-80", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ a_base+24(FP), SI")
	g.w("\tMOVQ b_base+48(FP), BX")
	g.w("\tMOVQ n+72(FP), CX")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	g.w("\t%s (BX), Y0, Y0", mnem)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, BX")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// unary: func name_asm(dst, src []float32, n int, <args>). prep sets up constant
// YMM regs; body transforms Y0 (input->output) using scratch Y1 and consts.
func (g *gen) unary(name string, frame int, prep func(*gen), body func(*gen)) {
	g.w("// func %s_asm(dst, src []float32, n int, ...)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-%d", name, frame)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	if prep != nil {
		prep(g)
	}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	body(g)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

func main() {
	g := &gen{}
	g.header()

	g.binary("add", "VADDPS")
	g.binary("sub", "VSUBPS")
	g.binary("mul", "VMULPS")
	g.binary("div", "VDIVPS")
	g.binary("maxpair", "VMAXPS")
	g.binary("minpair", "VMINPS")

	// relu: Y0 = max(Y0, 0)
	g.unary("relu", 56, func(g *gen) { g.w("\tVXORPS Y15, Y15, Y15") }, func(g *gen) {
		g.w("\tVMAXPS Y15, Y0, Y0")
	})

	// hardswish: t = clamp(x/6+0.5,0,1); out = x*t
	prepHS := func(g *gen) {
		g.w("\tVBROADCASTSS c_sixth<>(SB), Y13")
		g.w("\tVBROADCASTSS c_half<>(SB), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardswish", 56, prepHS, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1        // t = 0.5")
		g.w("\tVFMADD231PS Y13, Y0, Y1 // t += (1/6)*x")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMULPS Y1, Y0, Y0      // out = x*t")
	})

	// hardsigmoid(alpha,beta): clamp(alpha*x+beta,0,1)
	prepHSig := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVBROADCASTSS beta+60(FP), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardsigmoid", 64, prepHSig, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1")
		g.w("\tVFMADD231PS Y13, Y0, Y1")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMOVUPS Y1, Y0")
	})

	// clip(lo,hi)
	prepClip := func(g *gen) {
		g.w("\tVBROADCASTSS lo+56(FP), Y14")
		g.w("\tVBROADCASTSS hi+60(FP), Y15")
	}
	g.unary("clip", 64, prepClip, func(g *gen) {
		g.w("\tVMAXPS Y14, Y0, Y0")
		g.w("\tVMINPS Y15, Y0, Y0")
	})

	// leakyrelu(alpha): max(x,0) + alpha*min(x,0)
	prepLeaky := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("leakyrelu", 60, prepLeaky, func(g *gen) {
		g.w("\tVMINPS Y15, Y0, Y1     // neg part")
		g.w("\tVMAXPS Y15, Y0, Y0     // pos part")
		g.w("\tVFMADD231PS Y13, Y1, Y0 // out = pos + alpha*neg")
	})

	prepScalar := func(g *gen) { g.w("\tVBROADCASTSS s+56(FP), Y13") }
	g.unary("addscalar", 60, prepScalar, func(g *gen) { g.w("\tVADDPS Y13, Y0, Y0") })
	g.unary("mulscalar", 60, prepScalar, func(g *gen) { g.w("\tVMULPS Y13, Y0, Y0") })

	g.axpy()
	g.dwconv(3)
	g.dwconv(5)

	os.Stdout.WriteString(g.b.String())
}

// axpy: dst += a*src.
func (g *gen) axpy() {
	g.w("// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src")
	g.w("TEXT ·axpy_asm(SB), NOSPLIT, $0-60")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS a+56(FP), Y13")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0")
	g.w("\tVMOVUPS (SI), Y1")
	g.w("\tVFMADD231PS Y13, Y1, Y0")
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwconv: one interior row of a stride-1 KxK depthwise conv, adding into dst.
// dst += sum_{kh,kw} wpacked[kh*K+kw] * src[kh*W + col + kw]. 8 cols/iter.
func (g *gen) dwconv(K int) {
	name := fmt.Sprintf("dwconv%dx%ds1", K, K)
	g.w("// func %s_asm(dst, src []float32, wpacked []float32, ncols, W int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-88", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ wpacked_base+48(FP), BX")
	g.w("\tMOVQ ncols+72(FP), CX")
	g.w("\tMOVQ W+80(FP), DX")
	g.w("\tSHLQ $2, DX // W in bytes")
	rows := []string{"R8", "R9", "R10", "R11", "R12"}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0 // acc = dst[c..c+8]")
	// set up row pointers R8..R(8+K-1) = SI + kh*DX
	g.w("\tMOVQ SI, %s", rows[0])
	for kh := 1; kh < K; kh++ {
		g.w("\tLEAQ (%s)(DX*1), %s", rows[kh-1], rows[kh])
	}
	for kh := 0; kh < K; kh++ {
		for kw := 0; kw < K; kw++ {
			t := kh*K + kw
			g.w("\tVBROADCASTSS %d(BX), Y1", t*4)
			g.w("\tVMOVUPS %d(%s), Y2", kw*4, rows[kh])
			g.w("\tVFMADD231PS Y1, Y2, Y0")
		}
	}
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, DI")
	g.w("\tADDQ $32, SI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}
