// Command genamd64 emits kernels/vek/vek_amd64.s: AVX2 f32 elementwise kernels
// (8-wide YMM). The Go amd64 assembler supports the AVX2 mnemonics directly, so
// no WORD encoding. Each kernel processes a multiple-of-8 element count; the Go
// wrapper in vek_amd64.go handles the <8 tail.
//
//	go run ./kernels/vek/genamd64 > kernels/vek/vek_amd64.s
package main

import (
	"fmt"
	"os"
	"strings"
)

type gen struct{ b strings.Builder }

func (g *gen) w(f string, a ...any) { fmt.Fprintf(&g.b, f+"\n", a...) }

func (g *gen) header() {
	g.w("// Code generated by kernels/vek/genamd64. DO NOT EDIT.")
	g.w("")
	g.w("//go:build amd64")
	g.w("")
	g.w(`#include "textflag.h"`)
	g.w("")
	// constants
	g.w("DATA c_sixth<>+0(SB)/4, $0.16666666666666666")
	g.w("GLOBL c_sixth<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_half<>+0(SB)/4, $0.5")
	g.w("GLOBL c_half<>(SB), RODATA|NOPTR, $4")
	g.w("DATA c_one<>+0(SB)/4, $1.0")
	g.w("GLOBL c_one<>(SB), RODATA|NOPTR, $4")
	for _, c := range expConsts {
		if c.sym == "c_one" {
			continue // declared above
		}
		g.w("DATA %s<>+0(SB)/4, $%v", c.sym, c.val)
		g.w("GLOBL %s<>(SB), RODATA|NOPTR, $4", c.sym)
	}
	g.w("")
}

// Exp constants (Cephes expf): x clamped to [lo,hi]; n = round(x·log2e);
// r = x − n·ln2 (hi/lo split); e^r ≈ 1 + r + r²·P(r); result = 2^n·e^r by
// adding n<<23 to the float bits. Below lo saturates at the smallest normal,
// above hi at ~2.3e38. Registers Y4..Y15 hold the constants, Y1..Y3 scratch.
var expConsts = []struct {
	reg int
	sym string
	val float64
}{
	{4, "c_explo", -87.33654}, {5, "c_exphi", 88.37626}, {6, "c_log2e", 1.44269504088896341},
	{7, "c_ln2hi", 0.693359375}, {8, "c_ln2lo", -2.12194440e-4},
	{9, "c_p0", 1.9875691500e-4}, {10, "c_p1", 1.3981999507e-3}, {11, "c_p2", 8.3334519073e-3},
	{12, "c_p3", 4.1665795894e-2}, {13, "c_p4", 1.6666665459e-1}, {14, "c_p5", 5.0000001201e-1},
	{15, "c_one", 1.0},
}

func expPrep(g *gen) {
	for _, c := range expConsts {
		g.w("\tVBROADCASTSS %s<>(SB), Y%d", c.sym, c.reg)
	}
}

// expBody: Y0 ← exp(Y0); clobbers Y1..Y3.
func expBody(g *gen) {
	g.w("\tVMAXPS Y4, Y0, Y0          // clamp lo")
	g.w("\tVMINPS Y5, Y0, Y0          // clamp hi")
	g.w("\tVMULPS Y6, Y0, Y1          // x*log2e")
	g.w("\tVROUNDPS $0, Y1, Y1        // n = round-to-nearest")
	g.w("\tVFNMADD231PS Y7, Y1, Y0    // r = x - n*ln2hi")
	g.w("\tVFNMADD231PS Y8, Y1, Y0    // r -= n*ln2lo")
	g.w("\tVMOVUPS Y10, Y2            // p1")
	g.w("\tVFMADD231PS Y9, Y0, Y2     // p0*r + p1")
	g.w("\tVMOVUPS Y11, Y3            // p2")
	g.w("\tVFMADD231PS Y2, Y0, Y3")
	g.w("\tVMOVUPS Y12, Y2            // p3")
	g.w("\tVFMADD231PS Y3, Y0, Y2")
	g.w("\tVMOVUPS Y13, Y3            // p4")
	g.w("\tVFMADD231PS Y2, Y0, Y3")
	g.w("\tVMOVUPS Y14, Y2            // p5")
	g.w("\tVFMADD231PS Y3, Y0, Y2     // P(r)")
	g.w("\tVMULPS Y0, Y0, Y3          // r^2")
	g.w("\tVADDPS Y15, Y0, Y0         // r+1")
	g.w("\tVFMADD231PS Y3, Y2, Y0     // += P*r^2")
	g.w("\tVCVTPS2DQ Y1, Y1           // n → int")
	g.w("\tVPSLLD $23, Y1, Y1")
	g.w("\tVPADDD Y1, Y0, Y0          // * 2^n")
}

// binary: func name_asm(dst, a, b []float32, n int); n multiple of 8.
func (g *gen) binary(name, mnem string) {
	g.w("// func %s_asm(dst, a, b []float32, n int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-80", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ a_base+24(FP), SI")
	g.w("\tMOVQ b_base+48(FP), BX")
	g.w("\tMOVQ n+72(FP), CX")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	g.w("\t%s (BX), Y0, Y0", mnem)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, BX")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// unary: func name_asm(dst, src []float32, n int, <args>). prep sets up constant
// YMM regs; body transforms Y0 (input->output) using scratch Y1 and consts.
func (g *gen) unary(name string, frame int, prep func(*gen), body func(*gen)) {
	g.w("// func %s_asm(dst, src []float32, n int, ...)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-%d", name, frame)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	if prep != nil {
		prep(g)
	}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (SI), Y0")
	body(g)
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

func main() {
	g := &gen{}
	g.header()

	g.binary("add", "VADDPS")
	g.binary("sub", "VSUBPS")
	g.binary("mul", "VMULPS")
	g.binary("div", "VDIVPS")
	g.binary("maxpair", "VMAXPS")
	g.binary("minpair", "VMINPS")

	// relu: Y0 = max(Y0, 0)
	g.unary("relu", 56, func(g *gen) { g.w("\tVXORPS Y15, Y15, Y15") }, func(g *gen) {
		g.w("\tVMAXPS Y15, Y0, Y0")
	})

	// hardswish: t = clamp(x/6+0.5,0,1); out = x*t
	prepHS := func(g *gen) {
		g.w("\tVBROADCASTSS c_sixth<>(SB), Y13")
		g.w("\tVBROADCASTSS c_half<>(SB), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardswish", 56, prepHS, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1        // t = 0.5")
		g.w("\tVFMADD231PS Y13, Y0, Y1 // t += (1/6)*x")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMULPS Y1, Y0, Y0      // out = x*t")
	})

	// hardsigmoid(alpha,beta): clamp(alpha*x+beta,0,1)
	prepHSig := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVBROADCASTSS beta+60(FP), Y14")
		g.w("\tVBROADCASTSS c_one<>(SB), Y12")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("hardsigmoid", 64, prepHSig, func(g *gen) {
		g.w("\tVMOVUPS Y14, Y1")
		g.w("\tVFMADD231PS Y13, Y0, Y1")
		g.w("\tVMAXPS Y15, Y1, Y1")
		g.w("\tVMINPS Y12, Y1, Y1")
		g.w("\tVMOVUPS Y1, Y0")
	})

	// clip(lo,hi)
	prepClip := func(g *gen) {
		g.w("\tVBROADCASTSS lo+56(FP), Y14")
		g.w("\tVBROADCASTSS hi+60(FP), Y15")
	}
	g.unary("clip", 64, prepClip, func(g *gen) {
		g.w("\tVMAXPS Y14, Y0, Y0")
		g.w("\tVMINPS Y15, Y0, Y0")
	})

	// leakyrelu(alpha): max(x,0) + alpha*min(x,0)
	prepLeaky := func(g *gen) {
		g.w("\tVBROADCASTSS alpha+56(FP), Y13")
		g.w("\tVXORPS Y15, Y15, Y15")
	}
	g.unary("leakyrelu", 60, prepLeaky, func(g *gen) {
		g.w("\tVMINPS Y15, Y0, Y1     // neg part")
		g.w("\tVMAXPS Y15, Y0, Y0     // pos part")
		g.w("\tVFMADD231PS Y13, Y1, Y0 // out = pos + alpha*neg")
	})

	prepScalar := func(g *gen) { g.w("\tVBROADCASTSS s+56(FP), Y13") }
	g.unary("addscalar", 60, prepScalar, func(g *gen) { g.w("\tVADDPS Y13, Y0, Y0") })
	g.unary("mulscalar", 60, prepScalar, func(g *gen) { g.w("\tVMULPS Y13, Y0, Y0") })

	g.unary("exp", 56, expPrep, expBody)
	g.unary("sigmoid", 56, expPrep, func(g *gen) {
		g.w("\tVXORPS Y1, Y1, Y1")
		g.w("\tVSUBPS Y0, Y1, Y0          // -x")
		expBody(g)
		g.w("\tVADDPS Y15, Y0, Y0         // 1+e^-x")
		g.w("\tVDIVPS Y0, Y15, Y0         // 1/(1+e^-x)")
	})

	g.axpy()
	for _, k := range dwShapes {
		g.dwconv(k[0], k[1])
	}

	os.Stdout.WriteString(g.b.String())
}

// axpy: dst += a*src.
func (g *gen) axpy() {
	g.w("// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src")
	g.w("TEXT ·axpy_asm(SB), NOSPLIT, $0-60")
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ n+48(FP), CX")
	g.w("\tVBROADCASTSS a+56(FP), Y13")
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0")
	g.w("\tVMOVUPS (SI), Y1")
	g.w("\tVFMADD231PS Y13, Y1, Y0")
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, SI")
	g.w("\tADDQ $32, DI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwconv: one interior row of a stride-1 KxK depthwise conv, adding into dst.
// dst += sum_{kh,kw} wpacked[kh*K+kw] * src[kh*W + col + kw]. 8 cols/iter.
func (g *gen) dwconv(KH, KW int) {
	name := fmt.Sprintf("dwconv%dx%ds1", KH, KW)
	g.w("// func %s_asm(dst, src []float32, wpacked []float32, ncols, W int)", name)
	g.w("TEXT ·%s_asm(SB), NOSPLIT, $0-88", name)
	g.w("\tMOVQ dst_base+0(FP), DI")
	g.w("\tMOVQ src_base+24(FP), SI")
	g.w("\tMOVQ wpacked_base+48(FP), BX")
	g.w("\tMOVQ ncols+72(FP), CX")
	g.w("\tMOVQ W+80(FP), DX")
	g.w("\tSHLQ $2, DX // W in bytes")
	rows := []string{"R8", "R9", "R10", "R11", "R12"}
	g.w("loop:")
	g.w("\tCMPQ CX, $8")
	g.w("\tJL done")
	g.w("\tVMOVUPS (DI), Y0 // acc = dst[c..c+8]")
	// set up row pointers R8..R(8+KH-1) = SI + kh*DX
	g.w("\tMOVQ SI, %s", rows[0])
	for kh := 1; kh < KH; kh++ {
		g.w("\tLEAQ (%s)(DX*1), %s", rows[kh-1], rows[kh])
	}
	for kh := 0; kh < KH; kh++ {
		for kw := 0; kw < KW; kw++ {
			t := kh*KW + kw
			g.w("\tVBROADCASTSS %d(BX), Y1", t*4)
			g.w("\tVMOVUPS %d(%s), Y2", kw*4, rows[kh])
			g.w("\tVFMADD231PS Y1, Y2, Y0")
		}
	}
	g.w("\tVMOVUPS Y0, (DI)")
	g.w("\tADDQ $32, DI")
	g.w("\tADDQ $32, SI")
	g.w("\tSUBQ $8, CX")
	g.w("\tJMP loop")
	g.w("done:")
	g.w("\tVZEROUPPER")
	g.w("\tRET")
	g.w("")
}

// dwShapes are the (KH, KW) depthwise row kernels generated (see ../gen).
var dwShapes = [][2]int{{3, 3}, {5, 5}, {3, 2}, {3, 1}, {5, 3}, {5, 2}}
