// Command genamd64 emits kernels/gemm/ukernel_amd64.s: an AVX2 6×16 f32 GEMM
// micro-kernel. Unlike arm64, the Go amd64 assembler supports the AVX2
// mnemonics directly (VFMADD231PS, VBROADCASTSS, VMOVUPS), so no WORD encoding.
//
//	go run ./kernels/gemm/genamd64 > kernels/gemm/ukernel_amd64.s
package main

import (
	"fmt"
	"os"
	"strings"
)

const (
	MR     = 6
	NR     = 16 // two YMM lanes of 8
	unroll = 4
)

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	acc := func(r, h int) string { return fmt.Sprintf("Y%d", r*2+h) } // Y0..Y11
	const bLo, bHi, bcast = "Y12", "Y13", "Y14"

	w("// Code generated by kernels/gemm/genamd64. DO NOT EDIT.")
	w("")
	w("//go:build amd64")
	w("")
	w(`#include "textflag.h"`)
	w("")
	w("// func microKernelAVX2(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool, bias []float32)")
	w("// 6x16 tile: acc[r] (Y%d..) += broadcast(ap[r]) * bp[0:16].", 0)
	w("TEXT ·microKernelAVX2(SB), NOSPLIT, $0-120")
	w("\tMOVQ kc+0(FP), DX")
	w("\tMOVQ ap_base+8(FP), AX")
	w("\tMOVQ bp_base+32(FP), BX")
	w("\tMOVQ c_base+56(FP), CX")
	w("\tMOVQ ldc+80(FP), DI")
	w("\tSHLQ $2, DI          // ldc in bytes")
	w("\tMOVBQZX accumulate+88(FP), SI")
	w("\tMOVQ bias_base+96(FP), R14")
	// Row pointers R8..R13 = c + r*ldc.
	w("\tMOVQ CX, R8")
	w("\tLEAQ (R8)(DI*1), R9")
	w("\tLEAQ (R9)(DI*1), R10")
	w("\tLEAQ (R10)(DI*1), R11")
	w("\tLEAQ (R11)(DI*1), R12")
	w("\tLEAQ (R12)(DI*1), R13")
	rows := []string{"R8", "R9", "R10", "R11", "R12", "R13"}
	// Accumulators always start at zero; when accumulating, C is added at the
	// store (C + sum) — the SAME grouping as the edge-tile spill (row += tile)
	// and the generic kernel, so a row's bits cannot depend on whether it went
	// through a full panel or an edge tile (batch invariance; the OCR rec
	// batch test caught the preload-vs-post-add mismatch end to end).
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", acc(r, 0), acc(r, 0), acc(r, 0))
		w("\tVXORPS %s, %s, %s", acc(r, 1), acc(r, 1), acc(r, 1))
	}
	w("kloop:")
	w("\tCMPQ DX, $%d", unroll)
	w("\tJL ktail")
	for u := 0; u < unroll; u++ {
		step(w, acc, bLo, bHi, bcast)
	}
	w("\tSUBQ $%d, DX", unroll)
	w("\tJMP kloop")
	w("ktail:")
	w("\tTESTQ DX, DX")
	w("\tJZ store")
	step(w, acc, bLo, bHi, bcast)
	w("\tDECQ DX")
	w("\tJMP ktail")
	w("store:")
	w("\tTESTQ SI, SI")
	w("\tJZ storeraw")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (%s), %s, %s", rows[r], acc(r, 0), acc(r, 0))
		w("\tVADDPS 32(%s), %s, %s", rows[r], acc(r, 1), acc(r, 1))
	}
	w("storeraw:")
	// Optional bias (nil = none): added after C, the same order as the
	// edge-tile spill (row = (C + sum) + bias).
	w("\tTESTQ R14, R14")
	w("\tJZ storenb")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (R14), %s, %s", acc(r, 0), acc(r, 0))
		w("\tVADDPS 32(R14), %s, %s", acc(r, 1), acc(r, 1))
	}
	w("storenb:")
	for r := 0; r < MR; r++ {
		w("\tVMOVUPS %s, (%s)", acc(r, 0), rows[r])
		w("\tVMOVUPS %s, 32(%s)", acc(r, 1), rows[r])
	}
	w("\tVZEROUPPER")
	w("\tRET")
	os.Stdout.WriteString(b.String())
}

// step emits one k iteration: load 16 B, then 6 broadcasts × 2 FMAs.
func step(w func(string, ...any), acc func(r, h int) string, bLo, bHi, bcast string) {
	w("\tVMOVUPS (BX), %s", bLo)
	w("\tVMOVUPS 32(BX), %s", bHi)
	w("\tADDQ $64, BX")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS (AX), %s", bcast)
		w("\tADDQ $4, AX")
		// acc += bcast * B  (Go order: VFMADD231PS src1, src2, dst => dst += src1*src2)
		w("\tVFMADD231PS %s, %s, %s", bcast, bLo, acc(r, 0))
		w("\tVFMADD231PS %s, %s, %s", bcast, bHi, acc(r, 1))
	}
}
