// Command genq emits kernels/gemm/qkernel_arm64.s: the u8×s8→s32 GEMM
// micro-kernel using USMMLA (FEAT_I8MM). Usage:
//
//	go run ./kernels/gemm/genq > kernels/gemm/qkernel_arm64.s
//
// Layout: C is an 8×12 s32 tile held as 4×6 2×2 blocks in v0..v23
// (v[bi*6+bj] = rows 2bi..2bi+1 × cols 2bj..2bj+1, row-major within the
// block, as USMMLA produces). Each loop iteration consumes one group of 8
// k-steps: A packed as 8 rows × 8 bytes (u8, v24..v27, a register per row
// pair), B as 12 columns × 8 bytes (s8, loaded in two waves through
// v28..v31); 24 USMMLA instructions accumulate 768 MACs.
package main

import (
	"fmt"
	"os"
	"strings"
)

func usmmla(d, n, m int) uint32 { return 0x4E80AC00 | uint32(m)<<16 | uint32(n)<<5 | uint32(d) }
func smmla(d, n, m int) uint32  { return 0x4E80A400 | uint32(m)<<16 | uint32(n)<<5 | uint32(d) }
func movi0(d int) uint32        { return 0x4F000400 | uint32(d) }

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	w("// Code generated by kernels/gemm/genq. DO NOT EDIT.")
	w("")
	w("//go:build arm64")
	w("")
	w(`#include "textflag.h"`)
	w("")
	emit(w, "qkernelU8S8", usmmla)
	emit(w, "qkernelS8S8", smmla)
	os.Stdout.WriteString(b.String())
}

// emit writes one 8×12 MMLA kernel; mma picks USMMLA (u8·s8) or SMMLA (s8·s8).
func emit(w func(string, ...any), name string, mma func(d, n, m int) uint32) {
	w("// func %s(kg int64, ap, bp, ct pointers)", name)
	w("// ct: 8×12 tile as 4×6 2×2 blocks (96 × s32); see package comment.")
	w("TEXT ·%s(SB), NOSPLIT, $0-32", name)
	w("\tMOVD kg+0(FP), R0")
	w("\tMOVD ap+8(FP), R1")
	w("\tMOVD bp+16(FP), R2")
	w("\tMOVD ct+24(FP), R3")
	for d := 0; d < 24; d++ {
		w("\tWORD $0x%08X // movi v%d.4s, #0", movi0(d), d)
	}
	w("%s_loop:", name)
	w("\tVLD1.P 64(R1), [V24.B16, V25.B16, V26.B16, V27.B16] // A rows 0-7 × 8k")
	w("\tVLD1.P 64(R2), [V28.B16, V29.B16, V30.B16, V31.B16] // B cols 0-7 × 8k")
	for bj := 0; bj < 4; bj++ {
		for bi := 0; bi < 4; bi++ {
			w("\tWORD $0x%08X // mmla v%d += a%d · b%d", mma(bi*6+bj, 24+bi, 28+bj), bi*6+bj, bi, bj)
		}
	}
	w("\tVLD1.P 32(R2), [V28.B16, V29.B16] // B cols 8-11 × 8k")
	for bj := 4; bj < 6; bj++ {
		for bi := 0; bi < 4; bi++ {
			w("\tWORD $0x%08X // mmla v%d += a%d · b%d", mma(bi*6+bj, 24+bi, 28+bj-4), bi*6+bj, bi, bj)
		}
	}
	w("\tSUBS $1, R0, R0")
	w("\tBNE  %s_loop", name)
	for base := 0; base < 24; base += 4 {
		w("\tVST1.P [V%d.S4, V%d.S4, V%d.S4, V%d.S4], 64(R3)", base, base+1, base+2, base+3)
	}
	w("\tRET")
	w("")
}
