//go:build arm64

package gemm

// microKernel is the active micro-kernel for this architecture.
var microKernel = microKernelARM64

// microKernelARM64 is the NEON 8×12 kernel in ukernel_arm64.s (generated by ./gen).
//
//go:noescape
func microKernelARM64(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool)
