//go:build amd64

package gemm

import "golang.org/x/sys/cpu"

// microKernel is the active micro-kernel for this architecture. The AVX2 kernel
// requires FMA + AVX2 (x86-64-v3, Haswell 2013+); on older CPUs we fall back to
// the portable Go micro-kernel so the binary runs everywhere rather than
// executing an illegal instruction. Detection is at process start (init), not
// per call.
var microKernel = pickMicroKernel()

// HasAVX2 reports whether the fast AVX2 GEMM path is active on this CPU.
var HasAVX2 = cpu.X86.HasAVX2 && cpu.X86.HasFMA

func pickMicroKernel() func(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool) {
	if HasAVX2 {
		return microKernelAVX2
	}
	return microKernelGeneric
}

// microKernelAVX2 is the AVX2 6×16 kernel in ukernel_amd64.s (generated by
// ./genamd64).
//
//go:noescape
func microKernelAVX2(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool)
