//go:build amd64

package gemm

// microKernel is the active micro-kernel for this architecture.
var microKernel = microKernelAVX2

// microKernelAVX2 is the AVX2 6×16 kernel in ukernel_amd64.s (generated by
// ./genamd64). Requires FMA + AVX2 (Haswell+, 2013 on).
//
//go:noescape
func microKernelAVX2(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool)
