// Command genqamd emits kernels/gemm/qkernel_amd64.s: AVX-512 VNNI int8 GEMM
// micro-kernels (VPDPBUSD — exact i32 accumulation, no i16 saturation stage,
// unlike the AVX2 vpmaddubsw formulation). Contract differs from the arm64
// MMLA kernels in two arch-owned ways: B is packed quad-major
// ([g][q(2)][j(12)][4] bytes, 16 bytes of tail slack for the 64-byte loads)
// and C is written row-major ([8][12] i32, masked 48-byte stores).
//
//	go run ./kernels/gemm/genqamd > kernels/gemm/qkernel_amd64.s
package main

import (
	"fmt"
	"strings"
)

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("// Code generated by kernels/gemm/genqamd. DO NOT EDIT.")
	w("")
	w("//go:build amd64")
	w("")
	w(`#include "textflag.h"`)
	w("")
	for _, signed := range []bool{false, true} {
		name := "qkernelU8S8VNNI"
		if signed {
			name = "qkernelS8S8VNNI"
		}
		w("// func %s(kg int64, ap *%s, bp *int8, ct *int32)", name, map[bool]string{false: "uint8", true: "int8"}[signed])
		w("// A [g][8r][8o], B quad-major [g][2q][12j][4] (+16B slack), C row-major 8x12.")
		w("TEXT ·%s(SB), NOSPLIT, $0-32", name)
		w("\tMOVQ kg+0(FP), DX")
		w("\tMOVQ ap+8(FP), AX")
		w("\tMOVQ bp+16(FP), BX")
		w("\tMOVQ ct+24(FP), CX")
		w("\tMOVL $0x0FFF, R8")
		w("\tKMOVW R8, K1")
		for r := 0; r < 8; r++ {
			w("\tVPXORD Z%d, Z%d, Z%d", r, r, r)
		}
		if signed {
			w("\tMOVL $0x80808080, R9")
			w("\tVPBROADCASTD R9, Z31 // sign-flip A: s8 -> u8")
			w("\tMOVL $0x01010101, R9")
			w("\tVPBROADCASTD R9, Z30 // ones for B column sums")
			w("\tVPXORD Z28, Z28, Z28 // per-column sum of B (for the +128 bias)")
		}
		w("%s_loop:", name)
		w("\tTESTQ DX, DX")
		w("\tJE %s_done", name)
		for q := 0; q < 2; q++ {
			w("\tVMOVDQU32 %d(BX), Z8 // B quad %d (48B + slack)", q*48, q)
			if signed {
				w("\tVPDPBUSD Z8, Z30, Z28 // column sums += ones·B")
			}
			for r := 0; r < 8; r++ {
				w("\tVPBROADCASTD %d(AX), Z9", r*8+q*4)
				if signed {
					w("\tVPXORD Z31, Z9, Z9")
				}
				w("\tVPDPBUSD Z8, Z9, Z%d", r)
			}
		}
		w("\tADDQ $64, AX")
		w("\tADDQ $96, BX")
		w("\tDECQ DX")
		w("\tJMP %s_loop", name)
		w("%s_done:", name)
		if signed {
			w("\tVPSLLD $7, Z28, Z28 // 128 * column sums")
			for r := 0; r < 8; r++ {
				w("\tVPSUBD Z28, Z%d, Z%d", r, r)
			}
		}
		for r := 0; r < 8; r++ {
			w("\tVMOVDQU32 Z%d, K1, %d(CX)", r, r*48)
		}
		w("\tRET")
		w("")
	}
	// bf16 kernel: identical skeleton with VDPBF16PS (BYTE-encoded — the Go
	// assembler has no AVX512-BF16 mnemonics) and f32 accumulators. A pair
	// (2×bf16) sits in each dword, so the "quad" blocks become pair blocks
	// with the same byte geometry.
	w("// func bkernelBF16DP(kg int64, ap *uint16, bp *uint16, ct *float32)")
	w("// A [g][8r][4×bf16=8B], B pair-major [g][2p][12j][2×bf16=4B] (+slack), C row-major 8x12 f32.")
	w("TEXT ·bkernelBF16DP(SB), NOSPLIT, $0-32")
	w("\tMOVQ kg+0(FP), DX")
	w("\tMOVQ ap+8(FP), AX")
	w("\tMOVQ bp+16(FP), BX")
	w("\tMOVQ ct+24(FP), CX")
	w("\tMOVL $0x0FFF, R8")
	w("\tKMOVW R8, K1")
	for r := 0; r < 8; r++ {
		w("\tVPXORD Z%d, Z%d, Z%d", r, r, r)
	}
	w("bf16dp_loop:")
	w("\tTESTQ DX, DX")
	w("\tJE bf16dp_done")
	for p := 0; p < 2; p++ {
		w("\tVMOVDQU32 %d(BX), Z8 // B pair block %d (48B + slack)", p*48, p)
		for r := 0; r < 8; r++ {
			w("\tVPBROADCASTD %d(AX), Z9", r*8+p*4)
			// VDPBF16PS Zr, Z9, Z8  (EVEX.512.F3.0F38.W0 52 /r)
			w("\tBYTE $0x62; BYTE $0xD2; BYTE $0x36; BYTE $0x48; BYTE $0x52; BYTE $0x%02X // VDPBF16PS Z8, Z9, Z%d", 0xC0|r<<3, r)
		}
	}
	w("\tADDQ $64, AX")
	w("\tADDQ $96, BX")
	w("\tDECQ DX")
	w("\tJMP bf16dp_loop")
	w("bf16dp_done:")
	for r := 0; r < 8; r++ {
		w("\tVMOVDQU32 Z%d, K1, %d(CX)", r, r*48)
	}
	w("\tVZEROUPPER")
	w("\tRET")
	w("")

	fmt.Print(b.String())
}
