// Command genamd512 emits kernels/gemm/ukernel_amd64_avx512.s: an AVX-512 6×16
// f32 GEMM micro-kernel sharing the MR=6/NR=16 tile (and packing) with the AVX2
// kernel. NR=16 fits in one ZMM, so a naive 6-accumulator version is FMA-latency
// bound on Zen4 (only 6-way ILP). To hide latency we keep TWO accumulator banks
// (Z0..Z5 and Z6..Z11 = 12-way ILP), fold two k steps per iteration into
// separate banks, and sum the banks at the end.
//
//	go run ./kernels/gemm/genamd512 > kernels/gemm/ukernel_amd64_avx512.s
package main

import (
	"fmt"
	"os"
	"strings"
)

const MR = 6

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	a0 := func(r int) string { return fmt.Sprintf("Z%d", r) }    // bank A: Z0..Z5
	a1 := func(r int) string { return fmt.Sprintf("Z%d", r+MR) } // bank B: Z6..Z11

	w("// Code generated by kernels/gemm/genamd512. DO NOT EDIT.")
	w("")
	w("//go:build amd64")
	w("")
	w(`#include "textflag.h"`)
	w("")
	w("// func microKernelAVX512(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool)")
	w("// 6x16 tile, NR=16 in one ZMM, two accumulator banks for ILP.")
	w("TEXT ·microKernelAVX512(SB), NOSPLIT, $0-89")
	w("\tMOVQ kc+0(FP), DX")
	w("\tMOVQ ap_base+8(FP), AX")
	w("\tMOVQ bp_base+32(FP), BX")
	w("\tMOVQ c_base+56(FP), CX")
	w("\tMOVQ ldc+80(FP), DI")
	w("\tSHLQ $2, DI")
	w("\tMOVBQZX accumulate+88(FP), SI")
	w("\tMOVQ CX, R8")
	w("\tLEAQ (R8)(DI*1), R9")
	w("\tLEAQ (R9)(DI*1), R10")
	w("\tLEAQ (R10)(DI*1), R11")
	w("\tLEAQ (R11)(DI*1), R12")
	w("\tLEAQ (R12)(DI*1), R13")
	rows := []string{"R8", "R9", "R10", "R11", "R12", "R13"}
	// Bank A starts from C (or zero); bank B always starts at zero.
	w("\tTESTQ SI, SI")
	w("\tJZ zeroA")
	for r := 0; r < MR; r++ {
		w("\tVMOVUPS (%s), %s", rows[r], a0(r))
	}
	w("\tJMP zeroB")
	w("zeroA:")
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", a0(r), a0(r), a0(r))
	}
	w("zeroB:")
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", a1(r), a1(r), a1(r))
	}
	// Pair loop: two k steps, one per bank.
	w("pair:")
	w("\tCMPQ DX, $2")
	w("\tJL tail")
	w("\tVMOVUPS (BX), Z16      // B[k]")
	w("\tVMOVUPS 64(BX), Z17    // B[k+1]")
	w("\tADDQ $128, BX")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z18", r*4)
		w("\tVBROADCASTSS %d(AX), Z19", 24+r*4)
		w("\tVFMADD231PS Z18, Z16, %s", a0(r))
		w("\tVFMADD231PS Z19, Z17, %s", a1(r))
	}
	w("\tADDQ $48, AX")
	w("\tSUBQ $2, DX")
	w("\tJMP pair")
	// Odd tail: one k into bank A.
	w("tail:")
	w("\tTESTQ DX, DX")
	w("\tJZ combine")
	w("\tVMOVUPS (BX), Z16")
	w("\tADDQ $64, BX")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z18", r*4)
		w("\tVFMADD231PS Z18, Z16, %s", a0(r))
	}
	w("\tADDQ $24, AX")
	w("combine:")
	for r := 0; r < MR; r++ {
		w("\tVADDPS %s, %s, %s", a1(r), a0(r), a0(r))
		w("\tVMOVUPS %s, (%s)", a0(r), rows[r])
	}
	w("\tVZEROUPPER")
	w("\tRET")
	os.Stdout.WriteString(b.String())
}
