// Command genamd512 emits kernels/gemm/ukernel_amd64_avx512.s: an AVX-512 6×16
// f32 GEMM micro-kernel sharing the MR=6/NR=16 tile (and packing) with the AVX2
// kernel. NR=16 fits in one ZMM, so a naive 6-accumulator version is FMA-latency
// bound on Zen4 (only 6-way ILP). To hide latency we keep TWO accumulator banks
// (Z0..Z5 and Z6..Z11 = 12-way ILP), fold two k steps per iteration into
// separate banks, and sum the banks at the end.
//
//	go run ./kernels/gemm/genamd512 > kernels/gemm/ukernel_amd64_avx512.s
package main

import (
	"fmt"
	"os"
	"strings"
)

const MR = 6

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	a0 := func(r int) string { return fmt.Sprintf("Z%d", r) }    // bank A: Z0..Z5
	a1 := func(r int) string { return fmt.Sprintf("Z%d", r+MR) } // bank B: Z6..Z11

	w("// Code generated by kernels/gemm/genamd512. DO NOT EDIT.")
	w("")
	w("//go:build amd64")
	w("")
	w(`#include "textflag.h"`)
	w("")
	w("// func microKernelAVX512(kc int, ap, bp []float32, c []float32, ldc int, accumulate bool, bias []float32)")
	w("// 6x16 tile, NR=16 in one ZMM, two accumulator banks for ILP.")
	w("TEXT ·microKernelAVX512(SB), NOSPLIT, $0-120")
	w("\tMOVQ kc+0(FP), DX")
	w("\tMOVQ ap_base+8(FP), AX")
	w("\tMOVQ bp_base+32(FP), BX")
	w("\tMOVQ c_base+56(FP), CX")
	w("\tMOVQ ldc+80(FP), DI")
	w("\tSHLQ $2, DI")
	w("\tMOVBQZX accumulate+88(FP), SI")
	w("\tMOVQ bias_base+96(FP), R14")
	w("\tMOVQ CX, R8")
	w("\tLEAQ (R8)(DI*1), R9")
	w("\tLEAQ (R9)(DI*1), R10")
	w("\tLEAQ (R10)(DI*1), R11")
	w("\tLEAQ (R11)(DI*1), R12")
	w("\tLEAQ (R12)(DI*1), R13")
	rows := []string{"R8", "R9", "R10", "R11", "R12", "R13"}
	// Both banks start at zero; when accumulating, C is added at the store
	// (C + (even+tail) + odd folded first) — the same grouping as the
	// edge-tile spill and the other kernels, so bits cannot depend on the
	// row's routing (full panel vs edge tile vs pair vs single).
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", a0(r), a0(r), a0(r))
	}
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", a1(r), a1(r), a1(r))
	}
	// Pair loop: two k steps, one per bank.
	w("pair:")
	w("\tCMPQ DX, $2")
	w("\tJL tail")
	w("\tVMOVUPS (BX), Z16      // B[k]")
	w("\tVMOVUPS 64(BX), Z17    // B[k+1]")
	w("\tADDQ $128, BX")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z18", r*4)
		w("\tVBROADCASTSS %d(AX), Z19", 24+r*4)
		w("\tVFMADD231PS Z18, Z16, %s", a0(r))
		w("\tVFMADD231PS Z19, Z17, %s", a1(r))
	}
	w("\tADDQ $48, AX")
	w("\tSUBQ $2, DX")
	w("\tJMP pair")
	// Odd tail: one k into bank A.
	w("tail:")
	w("\tTESTQ DX, DX")
	w("\tJZ combine")
	w("\tVMOVUPS (BX), Z16")
	w("\tADDQ $64, BX")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z18", r*4)
		w("\tVFMADD231PS Z18, Z16, %s", a0(r))
	}
	w("\tADDQ $24, AX")
	w("combine:")
	for r := 0; r < MR; r++ {
		w("\tVADDPS %s, %s, %s", a1(r), a0(r), a0(r))
	}
	w("\tTESTQ SI, SI")
	w("\tJZ storeraw")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (%s), %s, %s", rows[r], a0(r), a0(r))
	}
	w("storeraw:")
	// Optional bias (nil = none), added after C like the edge-tile spill.
	w("\tTESTQ R14, R14")
	w("\tJZ storenb")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (R14), %s, %s", a0(r), a0(r))
	}
	w("storenb:")
	for r := 0; r < MR; r++ {
		w("\tVMOVUPS %s, (%s)", a0(r), rows[r])
	}
	w("\tVZEROUPPER")
	w("\tRET")

	// Paired-panel kernel: 6×32 (two adjacent NR=16 panels). Each A broadcast
	// feeds two FMAs, cutting the load:FMA ratio from 14:12 (the banked 6×16
	// kernel's ceiling — broadcasts are loads) to 16:24.
	//
	// The accumulation structure MIRRORS the single kernel exactly — even-k
	// bank (preloaded with C when accumulating), odd-k bank (zeroed), odd
	// tail into the even bank, banks folded at the end — so a row computed by
	// the paired kernel is BIT-IDENTICAL to two single-kernel calls. The
	// scheduling layer routes rows through pairs or singles depending on m
	// and worker feed; without matching grouping that made results depend on
	// batch size (the OCR rec batch test caught it end to end).
	// Register plan: even accs Z0..Z11 (row-major, panel pairs), odd accs
	// Z12..Z23, B vectors Z24..Z27 (p0/p1 × even/odd), broadcasts Z28/Z29.
	w("")
	w("// func microKernel2AVX512(kc int, ap, bp0, bp1 []float32, c []float32, ldc int, accumulate bool, bias []float32)")
	w("// 6x32 tile over two adjacent packed panels; c covers 32 columns.")
	w("TEXT ·microKernel2AVX512(SB), NOSPLIT, $0-144")
	w("\tMOVQ kc+0(FP), DX")
	w("\tMOVQ ap_base+8(FP), AX")
	w("\tMOVQ bp0_base+32(FP), BX")
	w("\tMOVQ bp1_base+56(FP), SI")
	w("\tMOVQ c_base+80(FP), CX")
	w("\tMOVQ ldc+104(FP), DI")
	w("\tSHLQ $2, DI")
	w("\tMOVBQZX accumulate+112(FP), R14")
	w("\tMOVQ bias_base+120(FP), R15")
	w("\tMOVQ CX, R8")
	w("\tLEAQ (R8)(DI*1), R9")
	w("\tLEAQ (R9)(DI*1), R10")
	w("\tLEAQ (R10)(DI*1), R11")
	w("\tLEAQ (R11)(DI*1), R12")
	w("\tLEAQ (R12)(DI*1), R13")
	rows2 := []string{"R8", "R9", "R10", "R11", "R12", "R13"}
	ev := func(r, p int) string { return fmt.Sprintf("Z%d", 2*r+p) }    // even-k bank
	od := func(r, p int) string { return fmt.Sprintf("Z%d", 12+2*r+p) } // odd-k bank
	for r := 0; r < MR; r++ {
		w("\tVXORPS %s, %s, %s", ev(r, 0), ev(r, 0), ev(r, 0))
		w("\tVXORPS %s, %s, %s", ev(r, 1), ev(r, 1), ev(r, 1))
		w("\tVXORPS %s, %s, %s", od(r, 0), od(r, 0), od(r, 0))
		w("\tVXORPS %s, %s, %s", od(r, 1), od(r, 1), od(r, 1))
	}
	w("p2pair:")
	w("\tCMPQ DX, $2")
	w("\tJL p2tail")
	w("\tVMOVUPS (BX), Z24      // B0[k]")
	w("\tVMOVUPS (SI), Z25      // B1[k]")
	w("\tVMOVUPS 64(BX), Z26    // B0[k+1]")
	w("\tVMOVUPS 64(SI), Z27    // B1[k+1]")
	w("\tADDQ $128, BX")
	w("\tADDQ $128, SI")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z28", r*4)
		w("\tVBROADCASTSS %d(AX), Z29", 24+r*4)
		w("\tVFMADD231PS Z28, Z24, %s", ev(r, 0))
		w("\tVFMADD231PS Z28, Z25, %s", ev(r, 1))
		w("\tVFMADD231PS Z29, Z26, %s", od(r, 0))
		w("\tVFMADD231PS Z29, Z27, %s", od(r, 1))
	}
	w("\tADDQ $48, AX")
	w("\tSUBQ $2, DX")
	w("\tJMP p2pair")
	w("p2tail:")
	w("\tTESTQ DX, DX")
	w("\tJZ p2combine")
	w("\tVMOVUPS (BX), Z24")
	w("\tVMOVUPS (SI), Z25")
	w("\tADDQ $64, BX")
	w("\tADDQ $64, SI")
	for r := 0; r < MR; r++ {
		w("\tVBROADCASTSS %d(AX), Z28", r*4)
		w("\tVFMADD231PS Z28, Z24, %s", ev(r, 0))
		w("\tVFMADD231PS Z28, Z25, %s", ev(r, 1))
	}
	w("\tADDQ $24, AX")
	w("p2combine:")
	for r := 0; r < MR; r++ {
		w("\tVADDPS %s, %s, %s", od(r, 0), ev(r, 0), ev(r, 0))
		w("\tVADDPS %s, %s, %s", od(r, 1), ev(r, 1), ev(r, 1))
	}
	w("\tTESTQ R14, R14")
	w("\tJZ p2storeraw")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (%s), %s, %s", rows2[r], ev(r, 0), ev(r, 0))
		w("\tVADDPS 64(%s), %s, %s", rows2[r], ev(r, 1), ev(r, 1))
	}
	w("p2storeraw:")
	w("\tTESTQ R15, R15")
	w("\tJZ p2storenb")
	for r := 0; r < MR; r++ {
		w("\tVADDPS (R15), %s, %s", ev(r, 0), ev(r, 0))
		w("\tVADDPS 64(R15), %s, %s", ev(r, 1), ev(r, 1))
	}
	w("p2storenb:")
	for r := 0; r < MR; r++ {
		w("\tVMOVUPS %s, (%s)", ev(r, 0), rows2[r])
		w("\tVMOVUPS %s, 64(%s)", ev(r, 1), rows2[r])
	}
	w("\tVZEROUPPER")
	w("\tRET")
	os.Stdout.WriteString(b.String())
}
