// Code generated by kernels/vek/gen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func add_asm(dst, a, b []float32, n int)
TEXT ·add_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24D400 // add v0,v0,v4
	WORD $0x4E25D421 // add v1,v1,v5
	WORD $0x4E26D442 // add v2,v2,v6
	WORD $0x4E27D463 // add v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func sub_asm(dst, a, b []float32, n int)
TEXT ·sub_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4D400 // sub v0,v0,v4
	WORD $0x4EA5D421 // sub v1,v1,v5
	WORD $0x4EA6D442 // sub v2,v2,v6
	WORD $0x4EA7D463 // sub v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mul_asm(dst, a, b []float32, n int)
TEXT ·mul_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24DC00 // mul v0,v0,v4
	WORD $0x6E25DC21 // mul v1,v1,v5
	WORD $0x6E26DC42 // mul v2,v2,v6
	WORD $0x6E27DC63 // mul v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24DC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func div_asm(dst, a, b []float32, n int)
TEXT ·div_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24FC00 // div v0,v0,v4
	WORD $0x6E25FC21 // div v1,v1,v5
	WORD $0x6E26FC42 // div v2,v2,v6
	WORD $0x6E27FC63 // div v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24FC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func maxpair_asm(dst, a, b []float32, n int)
TEXT ·maxpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24F400 // maxpair v0,v0,v4
	WORD $0x4E25F421 // maxpair v1,v1,v5
	WORD $0x4E26F442 // maxpair v2,v2,v6
	WORD $0x4E27F463 // maxpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func minpair_asm(dst, a, b []float32, n int)
TEXT ·minpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4F400 // minpair v0,v0,v4
	WORD $0x4EA5F421 // minpair v1,v1,v5
	WORD $0x4EA6F442 // minpair v2,v2,v6
	WORD $0x4EA7F463 // minpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func relu_asm(dst, src []float32, n int, ...)
TEXT ·relu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	WORD $0x4F00041C // movi v28.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	WORD $0x4E3CF421 // fmax v1,v1,v28
	WORD $0x4E3CF442 // fmax v2,v2,v28
	WORD $0x4E3CF463 // fmax v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardswish_asm(dst, src []float32, n int, ...)
TEXT ·hardswish_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $1042983595, R9 // 1/6 = 0.16666666666666666
	WORD $0x4E040D3C // dup v28.4s, w9
	MOVD $1056964608, R9 // 0.5 = 0.5
	WORD $0x4E040D3D // dup v29.4s, w9
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x6E31DC21 // fmul v1,v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x6E32DC42 // fmul v2,v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x6E33DC63 // fmul v3,v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardsigmoid_asm(dst, src []float32, n int, ...)
TEXT ·hardsigmoid_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	MOVWU beta+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (beta)
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x4EB11E21 // mov v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x4EB21E42 // mov v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x4EB31E63 // mov v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func clip_asm(dst, src []float32, n int, ...)
TEXT ·clip_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU lo+56(FP), R9
	WORD $0x4E040D3E // dup v30.4s, w9 (lo)
	MOVWU hi+60(FP), R9
	WORD $0x4E040D3F // dup v31.4s, w9 (hi)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	WORD $0x4E3EF421 // fmax v1,v1,v30
	WORD $0x4EBFF421 // fmin v1,v1,v31
	WORD $0x4E3EF442 // fmax v2,v2,v30
	WORD $0x4EBFF442 // fmin v2,v2,v31
	WORD $0x4E3EF463 // fmax v3,v3,v30
	WORD $0x4EBFF463 // fmin v3,v3,v31
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func leakyrelu_asm(dst, src []float32, n int, ...)
TEXT ·leakyrelu_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	WORD $0x4F00041E // movi v30.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	WORD $0x4EBEF431 // fmin v17=min(v1,0)
	WORD $0x4E3EF421 // fmax v1=max(v1,0)
	WORD $0x4E3CCE21 // fmla v1+=v17*v28
	WORD $0x4EBEF452 // fmin v18=min(v2,0)
	WORD $0x4E3EF442 // fmax v2=max(v2,0)
	WORD $0x4E3CCE42 // fmla v2+=v18*v28
	WORD $0x4EBEF473 // fmin v19=min(v3,0)
	WORD $0x4E3EF463 // fmax v3=max(v3,0)
	WORD $0x4E3CCE63 // fmla v3+=v19*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func addscalar_asm(dst, src []float32, n int, ...)
TEXT ·addscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	WORD $0x4E3CD421 // fadd v1,v1,v28
	WORD $0x4E3CD442 // fadd v2,v2,v28
	WORD $0x4E3CD463 // fadd v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mulscalar_asm(dst, src []float32, n int, ...)
TEXT ·mulscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	WORD $0x6E3CDC21 // fmul v1,v1,v28
	WORD $0x6E3CDC42 // fmul v2,v2,v28
	WORD $0x6E3CDC63 // fmul v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src
TEXT ·axpy_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU a+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (a)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1 (R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	WORD $0x4E3CCCA1 // fmla v1 += v5*v28
	WORD $0x4E3CCCC2 // fmla v2 += v6*v28
	WORD $0x4E3CCCE3 // fmla v3 += v7*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4]
	VLD1.P 16(R1), [V4.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func dwconv3x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x5s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x5s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1.P 64(R2), [V25.S4, V26.S4, V27.S4, V28.S4]
	VLD1 (R2), [V29.S4, V30.S4, V31.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1820 // fmla v0 += v1 * v27.s[2] (w10)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1820 // fmla v0 += v1 * v27.s[3] (w11)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1020 // fmla v0 += v1 * v28.s[0] (w12)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1020 // fmla v0 += v1 * v28.s[1] (w13)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1820 // fmla v0 += v1 * v28.s[2] (w14)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1820 // fmla v0 += v1 * v28.s[3] (w15)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1020 // fmla v0 += v1 * v29.s[0] (w16)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1020 // fmla v0 += v1 * v29.s[1] (w17)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1820 // fmla v0 += v1 * v29.s[2] (w18)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1820 // fmla v0 += v1 * v29.s[3] (w19)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1020 // fmla v0 += v1 * v30.s[0] (w20)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1020 // fmla v0 += v1 * v30.s[1] (w21)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1820 // fmla v0 += v1 * v30.s[2] (w22)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1820 // fmla v0 += v1 * v30.s[3] (w23)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9F1020 // fmla v0 += v1 * v31.s[0] (w24)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

