// Code generated by kernels/vek/genamd64. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA c_sixth<>+0(SB)/4, $0.16666666666666666
GLOBL c_sixth<>(SB), RODATA|NOPTR, $4
DATA c_half<>+0(SB)/4, $0.5
GLOBL c_half<>(SB), RODATA|NOPTR, $4
DATA c_one<>+0(SB)/4, $1.0
GLOBL c_one<>(SB), RODATA|NOPTR, $4

// func add_asm(dst, a, b []float32, n int)
TEXT ·add_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VADDPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func sub_asm(dst, a, b []float32, n int)
TEXT ·sub_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VSUBPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func mul_asm(dst, a, b []float32, n int)
TEXT ·mul_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMULPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func div_asm(dst, a, b []float32, n int)
TEXT ·div_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VDIVPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func maxpair_asm(dst, a, b []float32, n int)
TEXT ·maxpair_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func minpair_asm(dst, a, b []float32, n int)
TEXT ·minpair_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMINPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func relu_asm(dst, src []float32, n int, ...)
TEXT ·relu_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS Y15, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func hardswish_asm(dst, src []float32, n int, ...)
TEXT ·hardswish_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS c_sixth<>(SB), Y13
	VBROADCASTSS c_half<>(SB), Y14
	VBROADCASTSS c_one<>(SB), Y12
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMOVUPS Y14, Y1        // t = 0.5
	VFMADD231PS Y13, Y0, Y1 // t += (1/6)*x
	VMAXPS Y15, Y1, Y1
	VMINPS Y12, Y1, Y1
	VMULPS Y1, Y0, Y0      // out = x*t
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func hardsigmoid_asm(dst, src []float32, n int, ...)
TEXT ·hardsigmoid_asm(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS alpha+56(FP), Y13
	VBROADCASTSS beta+60(FP), Y14
	VBROADCASTSS c_one<>(SB), Y12
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMOVUPS Y14, Y1
	VFMADD231PS Y13, Y0, Y1
	VMAXPS Y15, Y1, Y1
	VMINPS Y12, Y1, Y1
	VMOVUPS Y1, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func clip_asm(dst, src []float32, n int, ...)
TEXT ·clip_asm(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS lo+56(FP), Y14
	VBROADCASTSS hi+60(FP), Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS Y14, Y0, Y0
	VMINPS Y15, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func leakyrelu_asm(dst, src []float32, n int, ...)
TEXT ·leakyrelu_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS alpha+56(FP), Y13
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMINPS Y15, Y0, Y1     // neg part
	VMAXPS Y15, Y0, Y0     // pos part
	VFMADD231PS Y13, Y1, Y0 // out = pos + alpha*neg
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func addscalar_asm(dst, src []float32, n int, ...)
TEXT ·addscalar_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS s+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VADDPS Y13, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func mulscalar_asm(dst, src []float32, n int, ...)
TEXT ·mulscalar_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS s+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMULPS Y13, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src
TEXT ·axpy_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS a+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0
	VMOVUPS (SI), Y1
	VFMADD231PS Y13, Y1, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv3x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x3s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 8(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 8(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 8(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv5x5s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x5s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	LEAQ (R10)(DX*1), R11
	LEAQ (R11)(DX*1), R12
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 8(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 12(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 16(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 8(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 12(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 36(BX), Y1
	VMOVUPS 16(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 40(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 44(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 48(BX), Y1
	VMOVUPS 8(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 52(BX), Y1
	VMOVUPS 12(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 56(BX), Y1
	VMOVUPS 16(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 60(BX), Y1
	VMOVUPS 0(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 64(BX), Y1
	VMOVUPS 4(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 68(BX), Y1
	VMOVUPS 8(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 72(BX), Y1
	VMOVUPS 12(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 76(BX), Y1
	VMOVUPS 16(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 80(BX), Y1
	VMOVUPS 0(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 84(BX), Y1
	VMOVUPS 4(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 88(BX), Y1
	VMOVUPS 8(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 92(BX), Y1
	VMOVUPS 12(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 96(BX), Y1
	VMOVUPS 16(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

