// Code generated by kernels/vek/genamd64. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA c_sixth<>+0(SB)/4, $0.16666666666666666
GLOBL c_sixth<>(SB), RODATA|NOPTR, $4
DATA c_half<>+0(SB)/4, $0.5
GLOBL c_half<>(SB), RODATA|NOPTR, $4
DATA c_one<>+0(SB)/4, $1.0
GLOBL c_one<>(SB), RODATA|NOPTR, $4
DATA c_explo<>+0(SB)/4, $-87.33654
GLOBL c_explo<>(SB), RODATA|NOPTR, $4
DATA c_exphi<>+0(SB)/4, $88.37626
GLOBL c_exphi<>(SB), RODATA|NOPTR, $4
DATA c_log2e<>+0(SB)/4, $1.4426950408889634
GLOBL c_log2e<>(SB), RODATA|NOPTR, $4
DATA c_ln2hi<>+0(SB)/4, $0.693359375
GLOBL c_ln2hi<>(SB), RODATA|NOPTR, $4
DATA c_ln2lo<>+0(SB)/4, $-0.00021219444
GLOBL c_ln2lo<>(SB), RODATA|NOPTR, $4
DATA c_p0<>+0(SB)/4, $0.000198756915
GLOBL c_p0<>(SB), RODATA|NOPTR, $4
DATA c_p1<>+0(SB)/4, $0.0013981999507
GLOBL c_p1<>(SB), RODATA|NOPTR, $4
DATA c_p2<>+0(SB)/4, $0.0083334519073
GLOBL c_p2<>(SB), RODATA|NOPTR, $4
DATA c_p3<>+0(SB)/4, $0.041665795894
GLOBL c_p3<>(SB), RODATA|NOPTR, $4
DATA c_p4<>+0(SB)/4, $0.16666665459
GLOBL c_p4<>(SB), RODATA|NOPTR, $4
DATA c_p5<>+0(SB)/4, $0.50000001201
GLOBL c_p5<>(SB), RODATA|NOPTR, $4

// func add_asm(dst, a, b []float32, n int)
TEXT ·add_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VADDPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func sub_asm(dst, a, b []float32, n int)
TEXT ·sub_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VSUBPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func mul_asm(dst, a, b []float32, n int)
TEXT ·mul_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMULPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func div_asm(dst, a, b []float32, n int)
TEXT ·div_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VDIVPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func maxpair_asm(dst, a, b []float32, n int)
TEXT ·maxpair_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func minpair_asm(dst, a, b []float32, n int)
TEXT ·minpair_asm(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ b_base+48(FP), BX
	MOVQ n+72(FP), CX
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMINPS (BX), Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, BX
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func relu_asm(dst, src []float32, n int, ...)
TEXT ·relu_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS Y15, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func hardswish_asm(dst, src []float32, n int, ...)
TEXT ·hardswish_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS c_sixth<>(SB), Y13
	VBROADCASTSS c_half<>(SB), Y14
	VBROADCASTSS c_one<>(SB), Y12
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMOVUPS Y14, Y1        // t = 0.5
	VFMADD231PS Y13, Y0, Y1 // t += (1/6)*x
	VMAXPS Y15, Y1, Y1
	VMINPS Y12, Y1, Y1
	VMULPS Y1, Y0, Y0      // out = x*t
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func hardsigmoid_asm(dst, src []float32, n int, ...)
TEXT ·hardsigmoid_asm(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS alpha+56(FP), Y13
	VBROADCASTSS beta+60(FP), Y14
	VBROADCASTSS c_one<>(SB), Y12
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMOVUPS Y14, Y1
	VFMADD231PS Y13, Y0, Y1
	VMAXPS Y15, Y1, Y1
	VMINPS Y12, Y1, Y1
	VMOVUPS Y1, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func clip_asm(dst, src []float32, n int, ...)
TEXT ·clip_asm(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS lo+56(FP), Y14
	VBROADCASTSS hi+60(FP), Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS Y14, Y0, Y0
	VMINPS Y15, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func leakyrelu_asm(dst, src []float32, n int, ...)
TEXT ·leakyrelu_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS alpha+56(FP), Y13
	VXORPS Y15, Y15, Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMINPS Y15, Y0, Y1     // neg part
	VMAXPS Y15, Y0, Y0     // pos part
	VFMADD231PS Y13, Y1, Y0 // out = pos + alpha*neg
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func addscalar_asm(dst, src []float32, n int, ...)
TEXT ·addscalar_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS s+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VADDPS Y13, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func mulscalar_asm(dst, src []float32, n int, ...)
TEXT ·mulscalar_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS s+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMULPS Y13, Y0, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func exp_asm(dst, src []float32, n int, ...)
TEXT ·exp_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS c_explo<>(SB), Y4
	VBROADCASTSS c_exphi<>(SB), Y5
	VBROADCASTSS c_log2e<>(SB), Y6
	VBROADCASTSS c_ln2hi<>(SB), Y7
	VBROADCASTSS c_ln2lo<>(SB), Y8
	VBROADCASTSS c_p0<>(SB), Y9
	VBROADCASTSS c_p1<>(SB), Y10
	VBROADCASTSS c_p2<>(SB), Y11
	VBROADCASTSS c_p3<>(SB), Y12
	VBROADCASTSS c_p4<>(SB), Y13
	VBROADCASTSS c_p5<>(SB), Y14
	VBROADCASTSS c_one<>(SB), Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VMAXPS Y4, Y0, Y0          // clamp lo
	VMINPS Y5, Y0, Y0          // clamp hi
	VMULPS Y6, Y0, Y1          // x*log2e
	VROUNDPS $0, Y1, Y1        // n = round-to-nearest
	VFNMADD231PS Y7, Y1, Y0    // r = x - n*ln2hi
	VFNMADD231PS Y8, Y1, Y0    // r -= n*ln2lo
	VMOVUPS Y10, Y2            // p1
	VFMADD231PS Y9, Y0, Y2     // p0*r + p1
	VMOVUPS Y11, Y3            // p2
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y12, Y2            // p3
	VFMADD231PS Y3, Y0, Y2
	VMOVUPS Y13, Y3            // p4
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y14, Y2            // p5
	VFMADD231PS Y3, Y0, Y2     // P(r)
	VMULPS Y0, Y0, Y3          // r^2
	VADDPS Y15, Y0, Y0         // r+1
	VFMADD231PS Y3, Y2, Y0     // += P*r^2
	VCVTPS2DQ Y1, Y1           // n → int
	VPSLLD $23, Y1, Y1
	VPADDD Y1, Y0, Y0          // * 2^n
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func silu_asm(dst, src []float32, n int, ...)
TEXT ·silu_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS c_explo<>(SB), Y4
	VBROADCASTSS c_exphi<>(SB), Y5
	VBROADCASTSS c_log2e<>(SB), Y6
	VBROADCASTSS c_ln2hi<>(SB), Y7
	VBROADCASTSS c_ln2lo<>(SB), Y8
	VBROADCASTSS c_p0<>(SB), Y9
	VBROADCASTSS c_p1<>(SB), Y10
	VBROADCASTSS c_p2<>(SB), Y11
	VBROADCASTSS c_p3<>(SB), Y12
	VBROADCASTSS c_p4<>(SB), Y13
	VBROADCASTSS c_p5<>(SB), Y14
	VBROADCASTSS c_one<>(SB), Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VXORPS Y1, Y1, Y1
	VSUBPS Y0, Y1, Y0          // -x
	VMAXPS Y4, Y0, Y0          // clamp lo
	VMINPS Y5, Y0, Y0          // clamp hi
	VMULPS Y6, Y0, Y1          // x*log2e
	VROUNDPS $0, Y1, Y1        // n = round-to-nearest
	VFNMADD231PS Y7, Y1, Y0    // r = x - n*ln2hi
	VFNMADD231PS Y8, Y1, Y0    // r -= n*ln2lo
	VMOVUPS Y10, Y2            // p1
	VFMADD231PS Y9, Y0, Y2     // p0*r + p1
	VMOVUPS Y11, Y3            // p2
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y12, Y2            // p3
	VFMADD231PS Y3, Y0, Y2
	VMOVUPS Y13, Y3            // p4
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y14, Y2            // p5
	VFMADD231PS Y3, Y0, Y2     // P(r)
	VMULPS Y0, Y0, Y3          // r^2
	VADDPS Y15, Y0, Y0         // r+1
	VFMADD231PS Y3, Y2, Y0     // += P*r^2
	VCVTPS2DQ Y1, Y1           // n → int
	VPSLLD $23, Y1, Y1
	VPADDD Y1, Y0, Y0          // * 2^n
	VADDPS Y15, Y0, Y0         // 1+e^-x
	VDIVPS Y0, Y15, Y0         // sigmoid
	VMULPS (SI), Y0, Y0        // * x (reload from source)
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func sigmoid_asm(dst, src []float32, n int, ...)
TEXT ·sigmoid_asm(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS c_explo<>(SB), Y4
	VBROADCASTSS c_exphi<>(SB), Y5
	VBROADCASTSS c_log2e<>(SB), Y6
	VBROADCASTSS c_ln2hi<>(SB), Y7
	VBROADCASTSS c_ln2lo<>(SB), Y8
	VBROADCASTSS c_p0<>(SB), Y9
	VBROADCASTSS c_p1<>(SB), Y10
	VBROADCASTSS c_p2<>(SB), Y11
	VBROADCASTSS c_p3<>(SB), Y12
	VBROADCASTSS c_p4<>(SB), Y13
	VBROADCASTSS c_p5<>(SB), Y14
	VBROADCASTSS c_one<>(SB), Y15
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (SI), Y0
	VXORPS Y1, Y1, Y1
	VSUBPS Y0, Y1, Y0          // -x
	VMAXPS Y4, Y0, Y0          // clamp lo
	VMINPS Y5, Y0, Y0          // clamp hi
	VMULPS Y6, Y0, Y1          // x*log2e
	VROUNDPS $0, Y1, Y1        // n = round-to-nearest
	VFNMADD231PS Y7, Y1, Y0    // r = x - n*ln2hi
	VFNMADD231PS Y8, Y1, Y0    // r -= n*ln2lo
	VMOVUPS Y10, Y2            // p1
	VFMADD231PS Y9, Y0, Y2     // p0*r + p1
	VMOVUPS Y11, Y3            // p2
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y12, Y2            // p3
	VFMADD231PS Y3, Y0, Y2
	VMOVUPS Y13, Y3            // p4
	VFMADD231PS Y2, Y0, Y3
	VMOVUPS Y14, Y2            // p5
	VFMADD231PS Y3, Y0, Y2     // P(r)
	VMULPS Y0, Y0, Y3          // r^2
	VADDPS Y15, Y0, Y0         // r+1
	VFMADD231PS Y3, Y2, Y0     // += P*r^2
	VCVTPS2DQ Y1, Y1           // n → int
	VPSLLD $23, Y1, Y1
	VPADDD Y1, Y0, Y0          // * 2^n
	VADDPS Y15, Y0, Y0         // 1+e^-x
	VDIVPS Y0, Y15, Y0         // 1/(1+e^-x)
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src
TEXT ·axpy_asm(SB), NOSPLIT, $0-60
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VBROADCASTSS a+56(FP), Y13
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0
	VMOVUPS (SI), Y1
	VFMADD231PS Y13, Y1, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv3x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x3s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 8(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 8(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 8(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv5x5s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x5s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	LEAQ (R10)(DX*1), R11
	LEAQ (R11)(DX*1), R12
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 8(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 12(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 16(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 8(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 12(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 36(BX), Y1
	VMOVUPS 16(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 40(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 44(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 48(BX), Y1
	VMOVUPS 8(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 52(BX), Y1
	VMOVUPS 12(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 56(BX), Y1
	VMOVUPS 16(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 60(BX), Y1
	VMOVUPS 0(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 64(BX), Y1
	VMOVUPS 4(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 68(BX), Y1
	VMOVUPS 8(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 72(BX), Y1
	VMOVUPS 12(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 76(BX), Y1
	VMOVUPS 16(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 80(BX), Y1
	VMOVUPS 0(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 84(BX), Y1
	VMOVUPS 4(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 88(BX), Y1
	VMOVUPS 8(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 92(BX), Y1
	VMOVUPS 12(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 96(BX), Y1
	VMOVUPS 16(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv3x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x2s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv3x1s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x1s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv5x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x3s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	LEAQ (R10)(DX*1), R11
	LEAQ (R11)(DX*1), R12
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 8(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 8(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 8(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 36(BX), Y1
	VMOVUPS 0(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 40(BX), Y1
	VMOVUPS 4(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 44(BX), Y1
	VMOVUPS 8(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 48(BX), Y1
	VMOVUPS 0(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 52(BX), Y1
	VMOVUPS 4(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 56(BX), Y1
	VMOVUPS 8(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dwconv5x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x2s1_asm(SB), NOSPLIT, $0-88
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ wpacked_base+48(FP), BX
	MOVQ ncols+72(FP), CX
	MOVQ W+80(FP), DX
	SHLQ $2, DX // W in bytes
loop:
	CMPQ CX, $8
	JL done
	VMOVUPS (DI), Y0 // acc = dst[c..c+8]
	MOVQ SI, R8
	LEAQ (R8)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	LEAQ (R10)(DX*1), R11
	LEAQ (R11)(DX*1), R12
	VBROADCASTSS 0(BX), Y1
	VMOVUPS 0(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 4(BX), Y1
	VMOVUPS 4(R8), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 8(BX), Y1
	VMOVUPS 0(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 12(BX), Y1
	VMOVUPS 4(R9), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 16(BX), Y1
	VMOVUPS 0(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 20(BX), Y1
	VMOVUPS 4(R10), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 24(BX), Y1
	VMOVUPS 0(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 28(BX), Y1
	VMOVUPS 4(R11), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 32(BX), Y1
	VMOVUPS 0(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VBROADCASTSS 36(BX), Y1
	VMOVUPS 4(R12), Y2
	VFMADD231PS Y1, Y2, Y0
	VMOVUPS Y0, (DI)
	ADDQ $32, DI
	ADDQ $32, SI
	SUBQ $8, CX
	JMP loop
done:
	VZEROUPPER
	RET

// func dot_asm(a, b []float32, n int, out []float32)
TEXT ·dot_asm(SB), NOSPLIT, $0-80
	MOVQ a_base+0(FP), SI
	MOVQ b_base+24(FP), BX
	MOVQ n+48(FP), CX
	MOVQ out_base+56(FP), DI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
loop:
	CMPQ CX, $32
	JL done
	VMOVUPS 0(SI), Y4
	VFMADD231PS 0(BX), Y4, Y0
	VMOVUPS 32(SI), Y5
	VFMADD231PS 32(BX), Y5, Y1
	VMOVUPS 64(SI), Y6
	VFMADD231PS 64(BX), Y6, Y2
	VMOVUPS 96(SI), Y7
	VFMADD231PS 96(BX), Y7, Y3
	ADDQ $128, SI
	ADDQ $128, BX
	SUBQ $32, CX
	JMP loop
done:
	VMOVUPS Y0, 0(DI)
	VMOVUPS Y1, 32(DI)
	VMOVUPS Y2, 64(DI)
	VMOVUPS Y3, 96(DI)
	VZEROUPPER
	RET

