// Code generated by kernels/vek/gen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func add_asm(dst, a, b []float32, n int)
TEXT ·add_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24D400 // add v0,v0,v4
	WORD $0x4E25D421 // add v1,v1,v5
	WORD $0x4E26D442 // add v2,v2,v6
	WORD $0x4E27D463 // add v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func sub_asm(dst, a, b []float32, n int)
TEXT ·sub_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4D400 // sub v0,v0,v4
	WORD $0x4EA5D421 // sub v1,v1,v5
	WORD $0x4EA6D442 // sub v2,v2,v6
	WORD $0x4EA7D463 // sub v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mul_asm(dst, a, b []float32, n int)
TEXT ·mul_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24DC00 // mul v0,v0,v4
	WORD $0x6E25DC21 // mul v1,v1,v5
	WORD $0x6E26DC42 // mul v2,v2,v6
	WORD $0x6E27DC63 // mul v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24DC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func div_asm(dst, a, b []float32, n int)
TEXT ·div_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24FC00 // div v0,v0,v4
	WORD $0x6E25FC21 // div v1,v1,v5
	WORD $0x6E26FC42 // div v2,v2,v6
	WORD $0x6E27FC63 // div v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24FC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func maxpair_asm(dst, a, b []float32, n int)
TEXT ·maxpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24F400 // maxpair v0,v0,v4
	WORD $0x4E25F421 // maxpair v1,v1,v5
	WORD $0x4E26F442 // maxpair v2,v2,v6
	WORD $0x4E27F463 // maxpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func minpair_asm(dst, a, b []float32, n int)
TEXT ·minpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4F400 // minpair v0,v0,v4
	WORD $0x4EA5F421 // minpair v1,v1,v5
	WORD $0x4EA6F442 // minpair v2,v2,v6
	WORD $0x4EA7F463 // minpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func relu_asm(dst, src []float32, n int, ...)
TEXT ·relu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	WORD $0x4F00041C // movi v28.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	WORD $0x4E3CF421 // fmax v1,v1,v28
	WORD $0x4E3CF442 // fmax v2,v2,v28
	WORD $0x4E3CF463 // fmax v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardswish_asm(dst, src []float32, n int, ...)
TEXT ·hardswish_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $1042983595, R9 // 1/6 = 0.16666666666666666
	WORD $0x4E040D3C // dup v28.4s, w9
	MOVD $1056964608, R9 // 0.5 = 0.5
	WORD $0x4E040D3D // dup v29.4s, w9
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x6E31DC21 // fmul v1,v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x6E32DC42 // fmul v2,v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x6E33DC63 // fmul v3,v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardsigmoid_asm(dst, src []float32, n int, ...)
TEXT ·hardsigmoid_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	MOVWU beta+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (beta)
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x4EB11E21 // mov v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x4EB21E42 // mov v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x4EB31E63 // mov v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func clip_asm(dst, src []float32, n int, ...)
TEXT ·clip_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU lo+56(FP), R9
	WORD $0x4E040D3E // dup v30.4s, w9 (lo)
	MOVWU hi+60(FP), R9
	WORD $0x4E040D3F // dup v31.4s, w9 (hi)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	WORD $0x4E3EF421 // fmax v1,v1,v30
	WORD $0x4EBFF421 // fmin v1,v1,v31
	WORD $0x4E3EF442 // fmax v2,v2,v30
	WORD $0x4EBFF442 // fmin v2,v2,v31
	WORD $0x4E3EF463 // fmax v3,v3,v30
	WORD $0x4EBFF463 // fmin v3,v3,v31
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func leakyrelu_asm(dst, src []float32, n int, ...)
TEXT ·leakyrelu_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	WORD $0x4F00041E // movi v30.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	WORD $0x4EBEF431 // fmin v17=min(v1,0)
	WORD $0x4E3EF421 // fmax v1=max(v1,0)
	WORD $0x4E3CCE21 // fmla v1+=v17*v28
	WORD $0x4EBEF452 // fmin v18=min(v2,0)
	WORD $0x4E3EF442 // fmax v2=max(v2,0)
	WORD $0x4E3CCE42 // fmla v2+=v18*v28
	WORD $0x4EBEF473 // fmin v19=min(v3,0)
	WORD $0x4E3EF463 // fmax v3=max(v3,0)
	WORD $0x4E3CCE63 // fmla v3+=v19*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func addscalar_asm(dst, src []float32, n int, ...)
TEXT ·addscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	WORD $0x4E3CD421 // fadd v1,v1,v28
	WORD $0x4E3CD442 // fadd v2,v2,v28
	WORD $0x4E3CD463 // fadd v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mulscalar_asm(dst, src []float32, n int, ...)
TEXT ·mulscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	WORD $0x6E3CDC21 // fmul v1,v1,v28
	WORD $0x6E3CDC42 // fmul v2,v2,v28
	WORD $0x6E3CDC63 // fmul v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func exp_asm(dst, src []float32, n int, ...)
TEXT ·exp_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func silu_asm(dst, src []float32, n int, ...)
TEXT ·silu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EA01C04 // v4 = x (copy)
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6E24DC00 // fmul v0 *= x
	WORD $0x4EA11C25 // v5 = x (copy)
	WORD $0x6EA0F821 // fneg v1
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E3BD421 // fadd v1 += 1
	WORD $0x6E21FF61 // fdiv v1 = 1/v1
	WORD $0x6E25DC21 // fmul v1 *= x
	WORD $0x4EA21C46 // v6 = x (copy)
	WORD $0x6EA0F842 // fneg v2
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E3BD442 // fadd v2 += 1
	WORD $0x6E22FF62 // fdiv v2 = 1/v2
	WORD $0x6E26DC42 // fmul v2 *= x
	WORD $0x4EA31C67 // v7 = x (copy)
	WORD $0x6EA0F863 // fneg v3
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	WORD $0x4E3BD463 // fadd v3 += 1
	WORD $0x6E23FF63 // fdiv v3 = 1/v3
	WORD $0x6E27DC63 // fmul v3 *= x
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EA01C04 // v4 = x (copy)
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6E24DC00 // fmul v0 *= x
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func sigmoid_asm(dst, src []float32, n int, ...)
TEXT ·sigmoid_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6EA0F821 // fneg v1
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E3BD421 // fadd v1 += 1
	WORD $0x6E21FF61 // fdiv v1 = 1/v1
	WORD $0x6EA0F842 // fneg v2
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E3BD442 // fadd v2 += 1
	WORD $0x6E22FF62 // fdiv v2 = 1/v2
	WORD $0x6EA0F863 // fneg v3
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	WORD $0x4E3BD463 // fadd v3 += 1
	WORD $0x6E23FF63 // fdiv v3 = 1/v3
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src
TEXT ·axpy_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU a+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (a)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1 (R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	WORD $0x4E3CCCA1 // fmla v1 += v5*v28
	WORD $0x4E3CCCC2 // fmla v2 += v6*v28
	WORD $0x4E3CCCE3 // fmla v3 += v7*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4]
	VLD1.P 16(R1), [V4.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func dot_asm(a, b []float32, n int, out []float32)
TEXT ·dot_asm(SB), NOSPLIT, $0-80
	MOVD a_base+0(FP), R0
	MOVD b_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD out_base+56(FP), R2
	WORD $0x4F000410 // movi v16.4s, #0
	WORD $0x4F000411 // movi v17.4s, #0
	WORD $0x4F000412 // movi v18.4s, #0
	WORD $0x4F000413 // movi v19.4s, #0
loop16:
	CMP $16, R3
	BLT done
	VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24CC10 // fmla v16 += v0*v4
	WORD $0x4E25CC31 // fmla v17 += v1*v5
	WORD $0x4E26CC52 // fmla v18 += v2*v6
	WORD $0x4E27CC73 // fmla v19 += v3*v7
	SUB $16, R3
	B loop16
done:
	VST1 [V16.S4, V17.S4, V18.S4, V19.S4], (R2)
	RET

// func dwconv3x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x5s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x5s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1.P 64(R2), [V25.S4, V26.S4, V27.S4, V28.S4]
	VLD1 (R2), [V29.S4, V30.S4, V31.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1820 // fmla v0 += v1 * v27.s[2] (w10)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1820 // fmla v0 += v1 * v27.s[3] (w11)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1020 // fmla v0 += v1 * v28.s[0] (w12)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1020 // fmla v0 += v1 * v28.s[1] (w13)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1820 // fmla v0 += v1 * v28.s[2] (w14)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1820 // fmla v0 += v1 * v28.s[3] (w15)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1020 // fmla v0 += v1 * v29.s[0] (w16)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1020 // fmla v0 += v1 * v29.s[1] (w17)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1820 // fmla v0 += v1 * v29.s[2] (w18)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1820 // fmla v0 += v1 * v29.s[3] (w19)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1020 // fmla v0 += v1 * v30.s[0] (w20)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1020 // fmla v0 += v1 * v30.s[1] (w21)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1820 // fmla v0 += v1 * v30.s[2] (w22)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1820 // fmla v0 += v1 * v30.s[3] (w23)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9F1020 // fmla v0 += v1 * v31.s[0] (w24)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv3x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x2s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv3x1s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x1s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4, V28.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1820 // fmla v0 += v1 * v27.s[2] (w10)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1820 // fmla v0 += v1 * v27.s[3] (w11)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1020 // fmla v0 += v1 * v28.s[0] (w12)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1020 // fmla v0 += v1 * v28.s[1] (w13)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1820 // fmla v0 += v1 * v28.s[2] (w14)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x2s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

