// Code generated by kernels/vek/gen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func add_asm(dst, a, b []float32, n int)
TEXT ·add_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24D400 // add v0,v0,v4
	WORD $0x4E25D421 // add v1,v1,v5
	WORD $0x4E26D442 // add v2,v2,v6
	WORD $0x4E27D463 // add v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func sub_asm(dst, a, b []float32, n int)
TEXT ·sub_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4D400 // sub v0,v0,v4
	WORD $0x4EA5D421 // sub v1,v1,v5
	WORD $0x4EA6D442 // sub v2,v2,v6
	WORD $0x4EA7D463 // sub v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4D400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mul_asm(dst, a, b []float32, n int)
TEXT ·mul_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24DC00 // mul v0,v0,v4
	WORD $0x6E25DC21 // mul v1,v1,v5
	WORD $0x6E26DC42 // mul v2,v2,v6
	WORD $0x6E27DC63 // mul v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24DC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func div_asm(dst, a, b []float32, n int)
TEXT ·div_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x6E24FC00 // div v0,v0,v4
	WORD $0x6E25FC21 // div v1,v1,v5
	WORD $0x6E26FC42 // div v2,v2,v6
	WORD $0x6E27FC63 // div v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x6E24FC00
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func maxpair_asm(dst, a, b []float32, n int)
TEXT ·maxpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24F400 // maxpair v0,v0,v4
	WORD $0x4E25F421 // maxpair v1,v1,v5
	WORD $0x4E26F442 // maxpair v2,v2,v6
	WORD $0x4E27F463 // maxpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4E24F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func minpair_asm(dst, a, b []float32, n int)
TEXT ·minpair_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4EA4F400 // minpair v0,v0,v4
	WORD $0x4EA5F421 // minpair v1,v1,v5
	WORD $0x4EA6F442 // minpair v2,v2,v6
	WORD $0x4EA7F463 // minpair v3,v3,v7
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	WORD $0x4EA4F400
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func relu_asm(dst, src []float32, n int, ...)
TEXT ·relu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	WORD $0x4F00041C // movi v28.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	WORD $0x4E3CF421 // fmax v1,v1,v28
	WORD $0x4E3CF442 // fmax v2,v2,v28
	WORD $0x4E3CF463 // fmax v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CF400 // fmax v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardswish_asm(dst, src []float32, n int, ...)
TEXT ·hardswish_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $1042983595, R9 // 1/6 = 0.16666666666666666
	WORD $0x4E040D3C // dup v28.4s, w9
	MOVD $1056964608, R9 // 0.5 = 0.5
	WORD $0x4E040D3D // dup v29.4s, w9
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x6E31DC21 // fmul v1,v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x6E32DC42 // fmul v2,v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x6E33DC63 // fmul v3,v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x6E30DC00 // fmul v0,v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func hardsigmoid_asm(dst, src []float32, n int, ...)
TEXT ·hardsigmoid_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	MOVWU beta+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (beta)
	WORD $0x4F00041E // movi v30.4s, #0
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3F // dup v31.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	WORD $0x4EBD1FB1 // mov v17,v29
	WORD $0x4E3CCC31 // fmla v17+=v1*v28
	WORD $0x4E3EF631 // fmax v17,v17,v30
	WORD $0x4EBFF631 // fmin v17,v17,v31
	WORD $0x4EB11E21 // mov v1,v17
	WORD $0x4EBD1FB2 // mov v18,v29
	WORD $0x4E3CCC52 // fmla v18+=v2*v28
	WORD $0x4E3EF652 // fmax v18,v18,v30
	WORD $0x4EBFF652 // fmin v18,v18,v31
	WORD $0x4EB21E42 // mov v2,v18
	WORD $0x4EBD1FB3 // mov v19,v29
	WORD $0x4E3CCC73 // fmla v19+=v3*v28
	WORD $0x4E3EF673 // fmax v19,v19,v30
	WORD $0x4EBFF673 // fmin v19,v19,v31
	WORD $0x4EB31E63 // mov v3,v19
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBD1FB0 // mov v16,v29
	WORD $0x4E3CCC10 // fmla v16+=v0*v28
	WORD $0x4E3EF610 // fmax v16,v16,v30
	WORD $0x4EBFF610 // fmin v16,v16,v31
	WORD $0x4EB01E00 // mov v0,v16
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func clip_asm(dst, src []float32, n int, ...)
TEXT ·clip_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU lo+56(FP), R9
	WORD $0x4E040D3E // dup v30.4s, w9 (lo)
	MOVWU hi+60(FP), R9
	WORD $0x4E040D3F // dup v31.4s, w9 (hi)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	WORD $0x4E3EF421 // fmax v1,v1,v30
	WORD $0x4EBFF421 // fmin v1,v1,v31
	WORD $0x4E3EF442 // fmax v2,v2,v30
	WORD $0x4EBFF442 // fmin v2,v2,v31
	WORD $0x4E3EF463 // fmax v3,v3,v30
	WORD $0x4EBFF463 // fmin v3,v3,v31
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3EF400 // fmax v0,v0,v30
	WORD $0x4EBFF400 // fmin v0,v0,v31
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func leakyrelu_asm(dst, src []float32, n int, ...)
TEXT ·leakyrelu_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU alpha+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (alpha)
	WORD $0x4F00041E // movi v30.4s, #0
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	WORD $0x4EBEF431 // fmin v17=min(v1,0)
	WORD $0x4E3EF421 // fmax v1=max(v1,0)
	WORD $0x4E3CCE21 // fmla v1+=v17*v28
	WORD $0x4EBEF452 // fmin v18=min(v2,0)
	WORD $0x4E3EF442 // fmax v2=max(v2,0)
	WORD $0x4E3CCE42 // fmla v2+=v18*v28
	WORD $0x4EBEF473 // fmin v19=min(v3,0)
	WORD $0x4E3EF463 // fmax v3=max(v3,0)
	WORD $0x4E3CCE63 // fmla v3+=v19*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EBEF410 // fmin v16=min(v0,0)
	WORD $0x4E3EF400 // fmax v0=max(v0,0)
	WORD $0x4E3CCE00 // fmla v0+=v16*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func addscalar_asm(dst, src []float32, n int, ...)
TEXT ·addscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	WORD $0x4E3CD421 // fadd v1,v1,v28
	WORD $0x4E3CD442 // fadd v2,v2,v28
	WORD $0x4E3CD463 // fadd v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E3CD400 // fadd v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func mulscalar_asm(dst, src []float32, n int, ...)
TEXT ·mulscalar_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU s+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (s)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	WORD $0x6E3CDC21 // fmul v1,v1,v28
	WORD $0x6E3CDC42 // fmul v2,v2,v28
	WORD $0x6E3CDC63 // fmul v3,v3,v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6E3CDC00 // fmul v0,v0,v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func exp_asm(dst, src []float32, n int, ...)
TEXT ·exp_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func silu_asm(dst, src []float32, n int, ...)
TEXT ·silu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EA01C04 // v4 = x (copy)
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6E24DC00 // fmul v0 *= x
	WORD $0x4EA11C25 // v5 = x (copy)
	WORD $0x6EA0F821 // fneg v1
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E3BD421 // fadd v1 += 1
	WORD $0x6E21FF61 // fdiv v1 = 1/v1
	WORD $0x6E25DC21 // fmul v1 *= x
	WORD $0x4EA21C46 // v6 = x (copy)
	WORD $0x6EA0F842 // fneg v2
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E3BD442 // fadd v2 += 1
	WORD $0x6E22FF62 // fdiv v2 = 1/v2
	WORD $0x6E26DC42 // fmul v2 *= x
	WORD $0x4EA31C67 // v7 = x (copy)
	WORD $0x6EA0F863 // fneg v3
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	WORD $0x4E3BD463 // fadd v3 += 1
	WORD $0x6E23FF63 // fdiv v3 = 1/v3
	WORD $0x6E27DC63 // fmul v3 *= x
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EA01C04 // v4 = x (copy)
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6E24DC00 // fmul v0 *= x
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func sigmoid_asm(dst, src []float32, n int, ...)
TEXT ·sigmoid_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
loop16:
	CMP $16, R3
	BLT loop4
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	WORD $0x6EA0F821 // fneg v1
	WORD $0x4E28F421 // fmax v1,lo
	WORD $0x4EA9F421 // fmin v1,hi
	WORD $0x6E2ADC3D // v29 = x*log2e
	WORD $0x4E218BBD // frintn v29 (n)
	WORD $0x4E2BCFA1 // r = x - n*ln2hi
	WORD $0x4E2CCFA1 // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E21CDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E21CEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E21CE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E21CEB1 // s += t*r  (P(r))
	WORD $0x6E21DC35 // t = r*r
	WORD $0x4E3BD421 // v = r+1
	WORD $0x4E35CE21 // v += P*r^2
	WORD $0x4E21ABBD // n → int
	WORD $0x4F3757BD // n << 23
	WORD $0x4EBD8421 // v = v * 2^n (int add)
	WORD $0x4E3BD421 // fadd v1 += 1
	WORD $0x6E21FF61 // fdiv v1 = 1/v1
	WORD $0x6EA0F842 // fneg v2
	WORD $0x4E28F442 // fmax v2,lo
	WORD $0x4EA9F442 // fmin v2,hi
	WORD $0x6E2ADC5E // v30 = x*log2e
	WORD $0x4E218BDE // frintn v30 (n)
	WORD $0x4E2BCFC2 // r = x - n*ln2hi
	WORD $0x4E2CCFC2 // r -= n*ln2lo
	WORD $0x4EAE1DD2 // v18 = p1
	WORD $0x4E22CDB2 // s += p0*r
	WORD $0x4EAF1DF6 // v22 = p2
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EB81F12 // v18 = p3
	WORD $0x4E22CED2 // s += t*r
	WORD $0x4EB91F36 // v22 = p4
	WORD $0x4E22CE56 // t += s*r
	WORD $0x4EBA1F52 // v18 = p5
	WORD $0x4E22CED2 // s += t*r  (P(r))
	WORD $0x6E22DC56 // t = r*r
	WORD $0x4E3BD442 // v = r+1
	WORD $0x4E36CE42 // v += P*r^2
	WORD $0x4E21ABDE // n → int
	WORD $0x4F3757DE // n << 23
	WORD $0x4EBE8442 // v = v * 2^n (int add)
	WORD $0x4E3BD442 // fadd v2 += 1
	WORD $0x6E22FF62 // fdiv v2 = 1/v2
	WORD $0x6EA0F863 // fneg v3
	WORD $0x4E28F463 // fmax v3,lo
	WORD $0x4EA9F463 // fmin v3,hi
	WORD $0x6E2ADC7F // v31 = x*log2e
	WORD $0x4E218BFF // frintn v31 (n)
	WORD $0x4E2BCFE3 // r = x - n*ln2hi
	WORD $0x4E2CCFE3 // r -= n*ln2lo
	WORD $0x4EAE1DD3 // v19 = p1
	WORD $0x4E23CDB3 // s += p0*r
	WORD $0x4EAF1DF7 // v23 = p2
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EB81F13 // v19 = p3
	WORD $0x4E23CEF3 // s += t*r
	WORD $0x4EB91F37 // v23 = p4
	WORD $0x4E23CE77 // t += s*r
	WORD $0x4EBA1F53 // v19 = p5
	WORD $0x4E23CEF3 // s += t*r  (P(r))
	WORD $0x6E23DC77 // t = r*r
	WORD $0x4E3BD463 // v = r+1
	WORD $0x4E37CE63 // v += P*r^2
	WORD $0x4E21ABFF // n → int
	WORD $0x4F3757FF // n << 23
	WORD $0x4EBF8463 // v = v * 2^n (int add)
	WORD $0x4E3BD463 // fadd v3 += 1
	WORD $0x6E23FF63 // fdiv v3 = 1/v3
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6EA0F800 // fneg v0
	WORD $0x4E28F400 // fmax v0,lo
	WORD $0x4EA9F400 // fmin v0,hi
	WORD $0x6E2ADC1C // v28 = x*log2e
	WORD $0x4E218B9C // frintn v28 (n)
	WORD $0x4E2BCF80 // r = x - n*ln2hi
	WORD $0x4E2CCF80 // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E20CDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E20CE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E20CE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E20CE90 // s += t*r  (P(r))
	WORD $0x6E20DC14 // t = r*r
	WORD $0x4E3BD400 // v = r+1
	WORD $0x4E34CE00 // v += P*r^2
	WORD $0x4E21AB9C // n → int
	WORD $0x4F37579C // n << 23
	WORD $0x4EBC8400 // v = v * 2^n (int add)
	WORD $0x4E3BD400 // fadd v0 += 1
	WORD $0x6E20FF60 // fdiv v0 = 1/v0
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func axpy_asm(dst, src []float32, n int, a float32): dst += a*src
TEXT ·axpy_asm(SB), NOSPLIT, $0-60
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU a+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (a)
loop16:
	CMP $16, R3
	BLT loop4
	VLD1 (R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	WORD $0x4E3CCCA1 // fmla v1 += v5*v28
	WORD $0x4E3CCCC2 // fmla v2 += v6*v28
	WORD $0x4E3CCCE3 // fmla v3 += v7*v28
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop4:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4]
	VLD1.P 16(R1), [V4.S4]
	WORD $0x4E3CCC80 // fmla v0 += v4*v28
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func dot_asm(a, b []float32, n int, out []float32)
TEXT ·dot_asm(SB), NOSPLIT, $0-80
	MOVD a_base+0(FP), R0
	MOVD b_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD out_base+56(FP), R2
	WORD $0x4F000410 // movi v16.4s, #0
	WORD $0x4F000411 // movi v17.4s, #0
	WORD $0x4F000412 // movi v18.4s, #0
	WORD $0x4F000413 // movi v19.4s, #0
loop16:
	CMP $16, R3
	BLT done
	VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
	WORD $0x4E24CC10 // fmla v16 += v0*v4
	WORD $0x4E25CC31 // fmla v17 += v1*v5
	WORD $0x4E26CC52 // fmla v18 += v2*v6
	WORD $0x4E27CC73 // fmla v19 += v3*v7
	SUB $16, R3
	B loop16
done:
	VST1 [V16.S4, V17.S4, V18.S4, V19.S4], (R2)
	RET

// func dotbf16_asm(a []float32, b []uint16, n int, out []float32)
TEXT ·dotbf16_asm(SB), NOSPLIT, $0-80
	MOVD a_base+0(FP), R0
	MOVD b_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD out_base+56(FP), R2
	WORD $0x4F000410 // movi v16.4s, #0
	WORD $0x4F000411 // movi v17.4s, #0
	WORD $0x4F000412 // movi v18.4s, #0
	WORD $0x4F000413 // movi v19.4s, #0
dotbf16_loop:
	CMP $16, R3
	BLT dotbf16_done
	VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 32(R1), [V4.H8, V5.H8]
	WORD $0x2E613886 // shll  v6.4s, v4.4h, #16
	WORD $0x6E613887 // shll2 v7.4s, v4.8h, #16
	WORD $0x4E26CC10 // fmla v16 += v0*v6
	WORD $0x4E27CC31 // fmla v17 += v1*v7
	WORD $0x2E6138A6 // shll  v6.4s, v5.4h, #16
	WORD $0x6E6138A7 // shll2 v7.4s, v5.8h, #16
	WORD $0x4E26CC52 // fmla v18 += v2*v6
	WORD $0x4E27CC73 // fmla v19 += v3*v7
	SUB $16, R3
	B dotbf16_loop
dotbf16_done:
	VST1 [V16.S4, V17.S4, V18.S4, V19.S4], (R2)
	RET

// func quantu8_asm(dst, src, n, scale, zp) — see quantKernels.
TEXT ·quantu8_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU scale+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (scale)
	MOVWU zp+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (zp)
quantu8_loop:
	CMP $16, R3
	BLT quantu8_done
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3CFC00 // fdiv v0 /= scale
	WORD $0x4E3DD400 // fadd v0 += zp
	WORD $0x4E21A800 // fcvtns v0
	WORD $0x6E3CFC21 // fdiv v1 /= scale
	WORD $0x4E3DD421 // fadd v1 += zp
	WORD $0x4E21A821 // fcvtns v1
	WORD $0x6E3CFC42 // fdiv v2 /= scale
	WORD $0x4E3DD442 // fadd v2 += zp
	WORD $0x4E21A842 // fcvtns v2
	WORD $0x6E3CFC63 // fdiv v3 /= scale
	WORD $0x4E3DD463 // fadd v3 += zp
	WORD $0x4E21A863 // fcvtns v3
	WORD $0x0E614804 // sqxtn v4.4h, v0.4s
	WORD $0x4E614824 // sqxtn2 v4.8h, v1.4s
	WORD $0x0E614845 // sqxtn v5.4h, v2.4s
	WORD $0x4E614865 // sqxtn2 v5.8h, v3.4s
	WORD $0x2E212886 // sqxtun v6.8b, v4.8h
	WORD $0x6E2128A6 // sqxtun2 v6.16b, v5.8h
	VST1.P [V6.B16], 16(R0)
	SUB $16, R3
	B quantu8_loop
quantu8_done:
	RET

// func quanti8_asm(dst, src, n, scale, zp) — see quantKernels.
TEXT ·quanti8_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU scale+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (scale)
	MOVWU zp+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (zp)
quanti8_loop:
	CMP $16, R3
	BLT quanti8_done
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3CFC00 // fdiv v0 /= scale
	WORD $0x4E3DD400 // fadd v0 += zp
	WORD $0x4E21A800 // fcvtns v0
	WORD $0x6E3CFC21 // fdiv v1 /= scale
	WORD $0x4E3DD421 // fadd v1 += zp
	WORD $0x4E21A821 // fcvtns v1
	WORD $0x6E3CFC42 // fdiv v2 /= scale
	WORD $0x4E3DD442 // fadd v2 += zp
	WORD $0x4E21A842 // fcvtns v2
	WORD $0x6E3CFC63 // fdiv v3 /= scale
	WORD $0x4E3DD463 // fadd v3 += zp
	WORD $0x4E21A863 // fcvtns v3
	WORD $0x0E614804 // sqxtn v4.4h, v0.4s
	WORD $0x4E614824 // sqxtn2 v4.8h, v1.4s
	WORD $0x0E614845 // sqxtn v5.4h, v2.4s
	WORD $0x4E614865 // sqxtn2 v5.8h, v3.4s
	WORD $0x0E214886 // sqxtn v6.8b, v4.8h
	WORD $0x4E2148A6 // sqxtn2 v6.16b, v5.8h
	VST1.P [V6.B16], 16(R0)
	SUB $16, R3
	B quanti8_loop
quanti8_done:
	RET

// func requantu8_asm(dst, src, n, mult, off, corr) — see quantKernels.
TEXT ·requantu8_asm(SB), NOSPLIT, $0-68
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU mult+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (mult)
	MOVWU off+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (off)
	MOVWU corr+64(FP), R9
	WORD $0x4E040D3B // dup v27.4s, w9 (corr)
requantu8_loop:
	CMP $16, R3
	BLT requantu8_done
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBB8400 // v0 += corr
	WORD $0x4E21D800 // scvtf v0
	WORD $0x6E3CDC00 // fmul v0 *= mult
	WORD $0x4E3DD400 // fadd v0 += off
	WORD $0x4E21A800 // fcvtns v0
	WORD $0x4EBB8421 // v1 += corr
	WORD $0x4E21D821 // scvtf v1
	WORD $0x6E3CDC21 // fmul v1 *= mult
	WORD $0x4E3DD421 // fadd v1 += off
	WORD $0x4E21A821 // fcvtns v1
	WORD $0x4EBB8442 // v2 += corr
	WORD $0x4E21D842 // scvtf v2
	WORD $0x6E3CDC42 // fmul v2 *= mult
	WORD $0x4E3DD442 // fadd v2 += off
	WORD $0x4E21A842 // fcvtns v2
	WORD $0x4EBB8463 // v3 += corr
	WORD $0x4E21D863 // scvtf v3
	WORD $0x6E3CDC63 // fmul v3 *= mult
	WORD $0x4E3DD463 // fadd v3 += off
	WORD $0x4E21A863 // fcvtns v3
	WORD $0x0E614804 // sqxtn v4.4h, v0.4s
	WORD $0x4E614824 // sqxtn2 v4.8h, v1.4s
	WORD $0x0E614845 // sqxtn v5.4h, v2.4s
	WORD $0x4E614865 // sqxtn2 v5.8h, v3.4s
	WORD $0x2E212886 // sqxtun v6.8b, v4.8h
	WORD $0x6E2128A6 // sqxtun2 v6.16b, v5.8h
	VST1.P [V6.B16], 16(R0)
	SUB $16, R3
	B requantu8_loop
requantu8_done:
	RET

// func requanti8_asm(dst, src, n, mult, off, corr) — see quantKernels.
TEXT ·requanti8_asm(SB), NOSPLIT, $0-68
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU mult+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (mult)
	MOVWU off+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (off)
	MOVWU corr+64(FP), R9
	WORD $0x4E040D3B // dup v27.4s, w9 (corr)
requanti8_loop:
	CMP $16, R3
	BLT requanti8_done
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4EBB8400 // v0 += corr
	WORD $0x4E21D800 // scvtf v0
	WORD $0x6E3CDC00 // fmul v0 *= mult
	WORD $0x4E3DD400 // fadd v0 += off
	WORD $0x4E21A800 // fcvtns v0
	WORD $0x4EBB8421 // v1 += corr
	WORD $0x4E21D821 // scvtf v1
	WORD $0x6E3CDC21 // fmul v1 *= mult
	WORD $0x4E3DD421 // fadd v1 += off
	WORD $0x4E21A821 // fcvtns v1
	WORD $0x4EBB8442 // v2 += corr
	WORD $0x4E21D842 // scvtf v2
	WORD $0x6E3CDC42 // fmul v2 *= mult
	WORD $0x4E3DD442 // fadd v2 += off
	WORD $0x4E21A842 // fcvtns v2
	WORD $0x4EBB8463 // v3 += corr
	WORD $0x4E21D863 // scvtf v3
	WORD $0x6E3CDC63 // fmul v3 *= mult
	WORD $0x4E3DD463 // fadd v3 += off
	WORD $0x4E21A863 // fcvtns v3
	WORD $0x0E614804 // sqxtn v4.4h, v0.4s
	WORD $0x4E614824 // sqxtn2 v4.8h, v1.4s
	WORD $0x0E614845 // sqxtn v5.4h, v2.4s
	WORD $0x4E614865 // sqxtn2 v5.8h, v3.4s
	WORD $0x0E214886 // sqxtn v6.8b, v4.8h
	WORD $0x4E2148A6 // sqxtn2 v6.16b, v5.8h
	VST1.P [V6.B16], 16(R0)
	SUB $16, R3
	B requanti8_loop
requanti8_done:
	RET

// func widens8_asm(dst, src, n) — s8 → s16 widen.
TEXT ·widens8_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
widens8_loop:
	CMP $16, R3
	BLT widens8_done
	VLD1.P 16(R1), [V0.B16]
	WORD $0x0F08A401 // sshll  v1.8h, v0.8b, #0
	WORD $0x4F08A402 // sshll2 v2.8h, v0.16b, #0
	VST1.P [V1.H8, V2.H8], 32(R0)
	SUB $16, R3
	B widens8_loop
widens8_done:
	RET

// func deint16_asm(ev, od, src, n) — even/odd de-interleave of s16.
TEXT ·deint16_asm(SB), NOSPLIT, $0-80
	MOVD ev_base+0(FP), R0
	MOVD od_base+24(FP), R1
	MOVD src_base+48(FP), R2
	MOVD n+72(FP), R3
deint16_loop:
	CMP $8, R3
	BLT deint16_done
	VLD1.P 32(R2), [V0.H8, V1.H8]
	WORD $0x4E411802 // uzp1.8h v2, v0, v1 (even)
	WORD $0x4E415803 // uzp2.8h v3, v0, v1 (odd)
	VST1.P [V2.H8], 16(R0)
	VST1.P [V3.H8], 16(R1)
	SUB $8, R3
	B deint16_loop
deint16_done:
	RET

// func zip2_asm(dst, a, b, n, c) — interleave with scalar add.
TEXT ·zip2_asm(SB), NOSPLIT, $0-84
	MOVD dst_base+0(FP), R0
	MOVD a_base+24(FP), R1
	MOVD b_base+48(FP), R2
	MOVD n+72(FP), R3
	MOVWU c+80(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (c)
zip2_loop:
	CMP $8, R3
	BLT zip2_done
	VLD1.P 32(R1), [V0.S4, V1.S4]
	VLD1.P 32(R2), [V2.S4, V3.S4]
	WORD $0x4E3CD400 // fadd v0 += c
	WORD $0x4E3CD421 // fadd v1 += c
	WORD $0x4E3CD442 // fadd v2 += c
	WORD $0x4E3CD463 // fadd v3 += c
	WORD $0x4E823804 // zip1.4s v4, v0, v2
	WORD $0x4E827805 // zip2.4s v5, v0, v2
	WORD $0x4E833826 // zip1.4s v6, v1, v3
	WORD $0x4E837827 // zip2.4s v7, v1, v3
	VST1.P [V4.S4, V5.S4, V6.S4, V7.S4], 64(R0)
	SUB $8, R3
	B zip2_loop
zip2_done:
	RET

// func shiftu8s8_asm(dst, src, n) — see quantKernels.
TEXT ·shiftu8s8_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	WORD $0x4F04E41C // movi v28.16b, #0x80
shiftu8s8_loop:
	CMP $64, R3
	BLT shiftu8s8_done
	VLD1.P 64(R1), [V0.B16, V1.B16, V2.B16, V3.B16]
	WORD $0x6E3C1C00 // eor v0 ^= 0x80
	WORD $0x6E3C1C21 // eor v1 ^= 0x80
	WORD $0x6E3C1C42 // eor v2 ^= 0x80
	WORD $0x6E3C1C63 // eor v3 ^= 0x80
	VST1.P [V0.B16, V1.B16, V2.B16, V3.B16], 64(R0)
	SUB $64, R3
	B shiftu8s8_loop
shiftu8s8_done:
	RET

// func dequantu8_asm(dst, src, n, scale, zp) — see quantKernels.
TEXT ·dequantu8_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU scale+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (scale)
	MOVWU zp+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (zp)
dequantu8_loop:
	CMP $16, R3
	BLT dequantu8_done
	VLD1.P 16(R1), [V0.B16]
	WORD $0x2F08A401 // widen bytes 0-7 → v1.8h
	WORD $0x6F08A402 // widen bytes 8-15 → v2.8h
	WORD $0x2F10A423 // v3.4s = lo(v1)
	WORD $0x6F10A424 // v4.4s = hi(v1)
	WORD $0x2F10A445 // v5.4s = lo(v2)
	WORD $0x6F10A446 // v6.4s = hi(v2)
	WORD $0x6EBD8463 // v3 -= zp
	WORD $0x4E21D863 // scvtf v3
	WORD $0x6E3CDC63 // fmul v3 *= scale
	WORD $0x6EBD8484 // v4 -= zp
	WORD $0x4E21D884 // scvtf v4
	WORD $0x6E3CDC84 // fmul v4 *= scale
	WORD $0x6EBD84A5 // v5 -= zp
	WORD $0x4E21D8A5 // scvtf v5
	WORD $0x6E3CDCA5 // fmul v5 *= scale
	WORD $0x6EBD84C6 // v6 -= zp
	WORD $0x4E21D8C6 // scvtf v6
	WORD $0x6E3CDCC6 // fmul v6 *= scale
	VST1.P [V3.S4, V4.S4, V5.S4, V6.S4], 64(R0)
	SUB $16, R3
	B dequantu8_loop
dequantu8_done:
	RET

// func dequanti8_asm(dst, src, n, scale, zp) — see quantKernels.
TEXT ·dequanti8_asm(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVWU scale+56(FP), R9
	WORD $0x4E040D3C // dup v28.4s, w9 (scale)
	MOVWU zp+60(FP), R9
	WORD $0x4E040D3D // dup v29.4s, w9 (zp)
dequanti8_loop:
	CMP $16, R3
	BLT dequanti8_done
	VLD1.P 16(R1), [V0.B16]
	WORD $0x0F08A401 // widen bytes 0-7 → v1.8h
	WORD $0x4F08A402 // widen bytes 8-15 → v2.8h
	WORD $0x0F10A423 // v3.4s = lo(v1)
	WORD $0x4F10A424 // v4.4s = hi(v1)
	WORD $0x0F10A445 // v5.4s = lo(v2)
	WORD $0x4F10A446 // v6.4s = hi(v2)
	WORD $0x6EBD8463 // v3 -= zp
	WORD $0x4E21D863 // scvtf v3
	WORD $0x6E3CDC63 // fmul v3 *= scale
	WORD $0x6EBD8484 // v4 -= zp
	WORD $0x4E21D884 // scvtf v4
	WORD $0x6E3CDC84 // fmul v4 *= scale
	WORD $0x6EBD84A5 // v5 -= zp
	WORD $0x4E21D8A5 // scvtf v5
	WORD $0x6E3CDCA5 // fmul v5 *= scale
	WORD $0x6EBD84C6 // v6 -= zp
	WORD $0x4E21D8C6 // scvtf v6
	WORD $0x6E3CDCC6 // fmul v6 *= scale
	VST1.P [V3.S4, V4.S4, V5.S4, V6.S4], 64(R0)
	SUB $16, R3
	B dequanti8_loop
dequanti8_done:
	RET

// func erf_asm(dst, src []float32, n int, ...)
TEXT ·erf_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
	MOVD $1051179525, R9 // p = 0.3275911
	WORD $0x4E040D22 // dup v2.4s, w9
	MOVD $1048738054, R9 // a1 = 0.254829592
	WORD $0x4E040D23 // dup v3.4s, w9
	MOVD $-1097750130, R9 // a2 = -0.284496736
	WORD $0x4E040D26 // dup v6.4s, w9
	MOVD $1068888291, R9 // a3 = 1.421413741
	WORD $0x4E040D27 // dup v7.4s, w9
	MOVD $-1078329117, R9 // a4 = -1.453152027
	WORD $0x4E040D36 // dup v22.4s, w9
	MOVD $1065868322, R9 // a5 = 1.061405429
	WORD $0x4E040D37 // dup v23.4s, w9
	MOVD $-2147483648, R9 // sign mask (0x80000000)
	WORD $0x4E040D3E // dup v30.4s, w9
loopN:
	CMP $8, R3
	BLT loop4
	VLD1.P 32(R1), [V0.S4, V1.S4]
	WORD $0x4EA0F804 // w = |x|
	WORD $0x6E24DC9C // u = x^2
	WORD $0x6EA0FB9C // u = -x^2
	WORD $0x4E28F79C // fmax v28,lo
	WORD $0x4EA9F79C // fmin v28,hi
	WORD $0x6E2ADF92 // v18 = x*log2e
	WORD $0x4E218A52 // frintn v18 (n)
	WORD $0x4E2BCE5C // r = x - n*ln2hi
	WORD $0x4E2CCE5C // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E3CCDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E3CCE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E3CCE90 // s += t*r  (P(r))
	WORD $0x6E3CDF94 // t = r*r
	WORD $0x4E3BD79C // v = r+1
	WORD $0x4E34CE1C // v += P*r^2
	WORD $0x4E21AA52 // n → int
	WORD $0x4F375652 // n << 23
	WORD $0x4EB2879C // v = v * 2^n (int add)
	WORD $0x4EBB1F74 // t = 1
	WORD $0x4E22CC94 // t += p*|x|
	WORD $0x6E34FF74 // t = 1/t
	WORD $0x4EB71EF0 // s = a5
	WORD $0x4EB61ED2 // u2 = a4
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA71CF0 // s = a3
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x4EA61CD2 // u2 = a2
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA31C70 // s = a1
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x6E34DE10 // s *= t
	WORD $0x6E3CDE10 // s *= e^{-x^2}
	WORD $0x4E3E1C04 // w = sign(x)
	WORD $0x4EB0D760 // x = 1 - s
	WORD $0x4EA41C00 // x |= sign
	WORD $0x4EA0F825 // w = |x|
	WORD $0x6E25DCBD // u = x^2
	WORD $0x6EA0FBBD // u = -x^2
	WORD $0x4E28F7BD // fmax v29,lo
	WORD $0x4EA9F7BD // fmin v29,hi
	WORD $0x6E2ADFB3 // v19 = x*log2e
	WORD $0x4E218A73 // frintn v19 (n)
	WORD $0x4E2BCE7D // r = x - n*ln2hi
	WORD $0x4E2CCE7D // r -= n*ln2lo
	WORD $0x4EAE1DD1 // v17 = p1
	WORD $0x4E3DCDB1 // s += p0*r
	WORD $0x4EAF1DF5 // v21 = p2
	WORD $0x4E3DCE35 // t += s*r
	WORD $0x4EB81F11 // v17 = p3
	WORD $0x4E3DCEB1 // s += t*r
	WORD $0x4EB91F35 // v21 = p4
	WORD $0x4E3DCE35 // t += s*r
	WORD $0x4EBA1F51 // v17 = p5
	WORD $0x4E3DCEB1 // s += t*r  (P(r))
	WORD $0x6E3DDFB5 // t = r*r
	WORD $0x4E3BD7BD // v = r+1
	WORD $0x4E35CE3D // v += P*r^2
	WORD $0x4E21AA73 // n → int
	WORD $0x4F375673 // n << 23
	WORD $0x4EB387BD // v = v * 2^n (int add)
	WORD $0x4EBB1F75 // t = 1
	WORD $0x4E22CCB5 // t += p*|x|
	WORD $0x6E35FF75 // t = 1/t
	WORD $0x4EB71EF1 // s = a5
	WORD $0x4EB61ED3 // u2 = a4
	WORD $0x4E35CE33 // u2 += s*t
	WORD $0x4EA71CF1 // s = a3
	WORD $0x4E35CE71 // s += u2*t
	WORD $0x4EA61CD3 // u2 = a2
	WORD $0x4E35CE33 // u2 += s*t
	WORD $0x4EA31C71 // s = a1
	WORD $0x4E35CE71 // s += u2*t
	WORD $0x6E35DE31 // s *= t
	WORD $0x6E3DDE31 // s *= e^{-x^2}
	WORD $0x4E3E1C25 // w = sign(x)
	WORD $0x4EB1D761 // x = 1 - s
	WORD $0x4EA51C21 // x |= sign
	VST1.P [V0.S4, V1.S4], 32(R0)
	SUB $8, R3
	B loopN
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x4EA0F804 // w = |x|
	WORD $0x6E24DC9C // u = x^2
	WORD $0x6EA0FB9C // u = -x^2
	WORD $0x4E28F79C // fmax v28,lo
	WORD $0x4EA9F79C // fmin v28,hi
	WORD $0x6E2ADF92 // v18 = x*log2e
	WORD $0x4E218A52 // frintn v18 (n)
	WORD $0x4E2BCE5C // r = x - n*ln2hi
	WORD $0x4E2CCE5C // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E3CCDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E3CCE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E3CCE90 // s += t*r  (P(r))
	WORD $0x6E3CDF94 // t = r*r
	WORD $0x4E3BD79C // v = r+1
	WORD $0x4E34CE1C // v += P*r^2
	WORD $0x4E21AA52 // n → int
	WORD $0x4F375652 // n << 23
	WORD $0x4EB2879C // v = v * 2^n (int add)
	WORD $0x4EBB1F74 // t = 1
	WORD $0x4E22CC94 // t += p*|x|
	WORD $0x6E34FF74 // t = 1/t
	WORD $0x4EB71EF0 // s = a5
	WORD $0x4EB61ED2 // u2 = a4
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA71CF0 // s = a3
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x4EA61CD2 // u2 = a2
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA31C70 // s = a1
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x6E34DE10 // s *= t
	WORD $0x6E3CDE10 // s *= e^{-x^2}
	WORD $0x4E3E1C04 // w = sign(x)
	WORD $0x4EB0D760 // x = 1 - s
	WORD $0x4EA41C00 // x |= sign
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func gelu_asm(dst, src []float32, n int, ...)
TEXT ·gelu_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD $-1028740017, R9 // lo = -87.33654
	WORD $0x4E040D28 // dup v8.4s, w9
	MOVD $1118879909, R9 // hi = 88.37626
	WORD $0x4E040D29 // dup v9.4s, w9
	MOVD $1069066811, R9 // log2e = 1.4426950408889634
	WORD $0x4E040D2A // dup v10.4s, w9
	MOVD $-1087275008, R9 // -ln2hi = -0.693359375
	WORD $0x4E040D2B // dup v11.4s, w9
	MOVD $962494595, R9 // -ln2lo = 0.00021219444
	WORD $0x4E040D2C // dup v12.4s, w9
	MOVD $961571175, R9 // p0 = 0.000198756915
	WORD $0x4E040D2D // dup v13.4s, w9
	MOVD $985088974, R9 // p1 = 0.0013981999507
	WORD $0x4E040D2E // dup v14.4s, w9
	MOVD $1007192328, R9 // p2 = 0.0083334519073
	WORD $0x4E040D2F // dup v15.4s, w9
	MOVD $1026206145, R9 // p3 = 0.041665795894
	WORD $0x4E040D38 // dup v24.4s, w9
	MOVD $1042983594, R9 // p4 = 0.16666665459
	WORD $0x4E040D39 // dup v25.4s, w9
	MOVD $1056964608, R9 // p5 = 0.50000001201
	WORD $0x4E040D3A // dup v26.4s, w9
	MOVD $1065353216, R9 // 1.0 = 1
	WORD $0x4E040D3B // dup v27.4s, w9
	MOVD $1051179525, R9 // p = 0.3275911
	WORD $0x4E040D22 // dup v2.4s, w9
	MOVD $1048738054, R9 // a1 = 0.254829592
	WORD $0x4E040D23 // dup v3.4s, w9
	MOVD $-1097750130, R9 // a2 = -0.284496736
	WORD $0x4E040D26 // dup v6.4s, w9
	MOVD $1068888291, R9 // a3 = 1.421413741
	WORD $0x4E040D27 // dup v7.4s, w9
	MOVD $-1078329117, R9 // a4 = -1.453152027
	WORD $0x4E040D36 // dup v22.4s, w9
	MOVD $1065868322, R9 // a5 = 1.061405429
	WORD $0x4E040D37 // dup v23.4s, w9
	MOVD $-2147483648, R9 // sign mask (0x80000000)
	WORD $0x4E040D3E // dup v30.4s, w9
	MOVD $1060439283, R9 // 1/sqrt2 = 0.7071067811865476
	WORD $0x4E040D21 // dup v1.4s, w9
	MOVD $1056964608, R9 // 0.5 = 0.5
	WORD $0x4E040D3F // dup v31.4s, w9
loop4:
	CMP $4, R3
	BLT done
	VLD1.P 16(R1), [V0.S4]
	WORD $0x6E21DC05 // v5 = x/sqrt2
	WORD $0x4EA0F8A4 // w = |x|
	WORD $0x6E24DC9C // u = x^2
	WORD $0x6EA0FB9C // u = -x^2
	WORD $0x4E28F79C // fmax v28,lo
	WORD $0x4EA9F79C // fmin v28,hi
	WORD $0x6E2ADF92 // v18 = x*log2e
	WORD $0x4E218A52 // frintn v18 (n)
	WORD $0x4E2BCE5C // r = x - n*ln2hi
	WORD $0x4E2CCE5C // r -= n*ln2lo
	WORD $0x4EAE1DD0 // v16 = p1
	WORD $0x4E3CCDB0 // s += p0*r
	WORD $0x4EAF1DF4 // v20 = p2
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EB81F10 // v16 = p3
	WORD $0x4E3CCE90 // s += t*r
	WORD $0x4EB91F34 // v20 = p4
	WORD $0x4E3CCE14 // t += s*r
	WORD $0x4EBA1F50 // v16 = p5
	WORD $0x4E3CCE90 // s += t*r  (P(r))
	WORD $0x6E3CDF94 // t = r*r
	WORD $0x4E3BD79C // v = r+1
	WORD $0x4E34CE1C // v += P*r^2
	WORD $0x4E21AA52 // n → int
	WORD $0x4F375652 // n << 23
	WORD $0x4EB2879C // v = v * 2^n (int add)
	WORD $0x4EBB1F74 // t = 1
	WORD $0x4E22CC94 // t += p*|x|
	WORD $0x6E34FF74 // t = 1/t
	WORD $0x4EB71EF0 // s = a5
	WORD $0x4EB61ED2 // u2 = a4
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA71CF0 // s = a3
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x4EA61CD2 // u2 = a2
	WORD $0x4E34CE12 // u2 += s*t
	WORD $0x4EA31C70 // s = a1
	WORD $0x4E34CE50 // s += u2*t
	WORD $0x6E34DE10 // s *= t
	WORD $0x6E3CDE10 // s *= e^{-x^2}
	WORD $0x4E3E1CA4 // w = sign(x)
	WORD $0x4EB0D765 // x = 1 - s
	WORD $0x4EA41CA5 // x |= sign
	WORD $0x4E3BD4A5 // v5 += 1
	WORD $0x6E25DC00 // v0 = x*(1+erf)
	WORD $0x6E3FDC00 // v0 *= 0.5
	VST1.P [V0.S4], 16(R0)
	SUB $4, R3
	B loop4
done:
	RET

// func dwconv3x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x5s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x5s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1.P 64(R2), [V25.S4, V26.S4, V27.S4, V28.S4]
	VLD1 (R2), [V29.S4, V30.S4, V31.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1820 // fmla v0 += v1 * v27.s[2] (w10)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1820 // fmla v0 += v1 * v27.s[3] (w11)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1020 // fmla v0 += v1 * v28.s[0] (w12)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1020 // fmla v0 += v1 * v28.s[1] (w13)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1820 // fmla v0 += v1 * v28.s[2] (w14)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1820 // fmla v0 += v1 * v28.s[3] (w15)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1020 // fmla v0 += v1 * v29.s[0] (w16)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1020 // fmla v0 += v1 * v29.s[1] (w17)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9D1820 // fmla v0 += v1 * v29.s[2] (w18)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBD1820 // fmla v0 += v1 * v29.s[3] (w19)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1020 // fmla v0 += v1 * v30.s[0] (w20)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1020 // fmla v0 += v1 * v30.s[1] (w21)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9E1820 // fmla v0 += v1 * v30.s[2] (w22)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBE1820 // fmla v0 += v1 * v30.s[3] (w23)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9F1020 // fmla v0 += v1 * v31.s[0] (w24)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv3x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x2s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv3x1s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv3x1s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x3s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4, V28.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1820 // fmla v0 += v1 * v27.s[2] (w10)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1820 // fmla v0 += v1 * v27.s[3] (w11)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1020 // fmla v0 += v1 * v28.s[0] (w12)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBC1020 // fmla v0 += v1 * v28.s[1] (w13)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9C1820 // fmla v0 += v1 * v28.s[2] (w14)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwconv5x2s1_asm(dst, src []float32, wpacked []float32, ncols, W int)
TEXT ·dwconv5x2s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wpacked_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $2, R4, R4 // row stride in bytes
	VLD1 (R2), [V25.S4, V26.S4, V27.S4]
loop:
	CMP $4, R3
	BLT done
	VLD1 (R0), [V0.S4] // acc = dst[c..c+4]
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991020 // fmla v0 += v1 * v25.s[0] (w0)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91020 // fmla v0 += v1 * v25.s[1] (w1)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F991820 // fmla v0 += v1 * v25.s[2] (w2)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FB91820 // fmla v0 += v1 * v25.s[3] (w3)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1020 // fmla v0 += v1 * v26.s[0] (w4)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1020 // fmla v0 += v1 * v26.s[1] (w5)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9A1820 // fmla v0 += v1 * v26.s[2] (w6)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBA1820 // fmla v0 += v1 * v26.s[3] (w7)
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4F9B1020 // fmla v0 += v1 * v27.s[0] (w8)
	ADD $4, R6, R6
	VLD1 (R6), [V1.S4]
	WORD $0x4FBB1020 // fmla v0 += v1 * v27.s[1] (w9)
	VST1.P [V0.S4], 16(R0)
	ADD $16, R1, R1
	SUB $4, R3, R3
	B loop
done:
	RET

// func dwblk8k3s1_asm(dst, src, w []float32, ncols, wp int)
TEXT ·dwblk8k3s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD w_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD wp+80(FP), R4
	LSL $5, R4, R4 // row stride bytes (wp*8*4)
	VLD1.P 64(R2), [V8.S4, V9.S4, V10.S4, V11.S4]
	VLD1.P 64(R2), [V12.S4, V13.S4, V14.S4, V15.S4]
	VLD1.P 64(R2), [V16.S4, V17.S4, V18.S4, V19.S4]
	VLD1.P 64(R2), [V20.S4, V21.S4, V22.S4, V23.S4]
	VLD1 (R2), [V24.S4, V25.S4]
	MOVD R1, R5
	ADD R4, R5, R6
	ADD R4, R6, R7
dwblk8k3s1_loop:
	CBZ R3, dwblk8k3s1_done
	MOVD R5, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x6E28DC40 // fmul v0 = v2*v8
	WORD $0x6E29DC61 // fmul v1 = v3*v9
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2ACC40 // fmla v0 += v2*v10
	WORD $0x4E2BCC61 // fmla v1 += v3*v11
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2CCC40 // fmla v0 += v2*v12
	WORD $0x4E2DCC61 // fmla v1 += v3*v13
	MOVD R6, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2ECC40 // fmla v0 += v2*v14
	WORD $0x4E2FCC61 // fmla v1 += v3*v15
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E30CC40 // fmla v0 += v2*v16
	WORD $0x4E31CC61 // fmla v1 += v3*v17
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E32CC40 // fmla v0 += v2*v18
	WORD $0x4E33CC61 // fmla v1 += v3*v19
	MOVD R7, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E34CC40 // fmla v0 += v2*v20
	WORD $0x4E35CC61 // fmla v1 += v3*v21
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E36CC40 // fmla v0 += v2*v22
	WORD $0x4E37CC61 // fmla v1 += v3*v23
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E38CC40 // fmla v0 += v2*v24
	WORD $0x4E39CC61 // fmla v1 += v3*v25
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $32, R5, R5
	ADD $32, R6, R6
	ADD $32, R7, R7
	SUB $1, R3, R3
	B dwblk8k3s1_loop
dwblk8k3s1_done:
	RET

// func dwblk8k3s2_asm(dst, src, w []float32, ncols, wp int)
TEXT ·dwblk8k3s2_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD w_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD wp+80(FP), R4
	LSL $5, R4, R4 // row stride bytes (wp*8*4)
	VLD1.P 64(R2), [V8.S4, V9.S4, V10.S4, V11.S4]
	VLD1.P 64(R2), [V12.S4, V13.S4, V14.S4, V15.S4]
	VLD1.P 64(R2), [V16.S4, V17.S4, V18.S4, V19.S4]
	VLD1.P 64(R2), [V20.S4, V21.S4, V22.S4, V23.S4]
	VLD1 (R2), [V24.S4, V25.S4]
	MOVD R1, R5
	ADD R4, R5, R6
	ADD R4, R6, R7
dwblk8k3s2_loop:
	CBZ R3, dwblk8k3s2_done
	MOVD R5, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x6E28DC40 // fmul v0 = v2*v8
	WORD $0x6E29DC61 // fmul v1 = v3*v9
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2ACC40 // fmla v0 += v2*v10
	WORD $0x4E2BCC61 // fmla v1 += v3*v11
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2CCC40 // fmla v0 += v2*v12
	WORD $0x4E2DCC61 // fmla v1 += v3*v13
	MOVD R6, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E2ECC40 // fmla v0 += v2*v14
	WORD $0x4E2FCC61 // fmla v1 += v3*v15
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E30CC40 // fmla v0 += v2*v16
	WORD $0x4E31CC61 // fmla v1 += v3*v17
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E32CC40 // fmla v0 += v2*v18
	WORD $0x4E33CC61 // fmla v1 += v3*v19
	MOVD R7, R8
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E34CC40 // fmla v0 += v2*v20
	WORD $0x4E35CC61 // fmla v1 += v3*v21
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E36CC40 // fmla v0 += v2*v22
	WORD $0x4E37CC61 // fmla v1 += v3*v23
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E38CC40 // fmla v0 += v2*v24
	WORD $0x4E39CC61 // fmla v1 += v3*v25
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $64, R5, R5
	ADD $64, R6, R6
	ADD $64, R7, R7
	SUB $1, R3, R3
	B dwblk8k3s2_loop
dwblk8k3s2_done:
	RET

// func dwblk8k5s1_asm(dst, src, w []float32, ncols, wp int)
TEXT ·dwblk8k5s1_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD w_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD wp+80(FP), R4
	LSL $5, R4, R4 // row stride bytes (wp*8*4)
	MOVD R1, R5
	ADD R4, R5, R6
	ADD R4, R6, R7
	ADD R4, R7, R10
	ADD R4, R10, R11
dwblk8k5s1_loop:
	CBZ R3, dwblk8k5s1_done
	MOVD R2, R12 // walk the packed taps
	MOVD R5, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x6E3ADC40 // fmul v0 = v2*v26
	WORD $0x6E3BDC61 // fmul v1 = v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R6, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R7, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R10, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R11, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $32, R5, R5
	ADD $32, R6, R6
	ADD $32, R7, R7
	ADD $32, R10, R10
	ADD $32, R11, R11
	SUB $1, R3, R3
	B dwblk8k5s1_loop
dwblk8k5s1_done:
	RET

// func dwblk8k5s2_asm(dst, src, w []float32, ncols, wp int)
TEXT ·dwblk8k5s2_asm(SB), NOSPLIT, $0-88
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD w_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD wp+80(FP), R4
	LSL $5, R4, R4 // row stride bytes (wp*8*4)
	MOVD R1, R5
	ADD R4, R5, R6
	ADD R4, R6, R7
	ADD R4, R7, R10
	ADD R4, R10, R11
dwblk8k5s2_loop:
	CBZ R3, dwblk8k5s2_done
	MOVD R2, R12 // walk the packed taps
	MOVD R5, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x6E3ADC40 // fmul v0 = v2*v26
	WORD $0x6E3BDC61 // fmul v1 = v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R6, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R7, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R10, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	MOVD R11, R8
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VLD1.P 32(R12), [V26.S4, V27.S4]
	VLD1.P 32(R8), [V2.S4, V3.S4]
	WORD $0x4E3ACC40 // fmla v0 += v2*v26
	WORD $0x4E3BCC61 // fmla v1 += v3*v27
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $64, R5, R5
	ADD $64, R6, R6
	ADD $64, R7, R7
	ADD $64, R10, R10
	ADD $64, R11, R11
	SUB $1, R3, R3
	B dwblk8k5s2_loop
dwblk8k5s2_done:
	RET

// func pwblk6x16_asm(dst0, dst1, x, w []float32, cin, xbstride int)
TEXT ·pwblk6x16_asm(SB), NOSPLIT, $0-112
	MOVD dst0_base+0(FP), R0
	MOVD dst1_base+24(FP), R1
	MOVD x_base+48(FP), R2
	MOVD w_base+72(FP), R3
	MOVD cin+96(FP), R4
	MOVD xbstride+104(FP), R5
	WORD $0x4F000400 // movi v0.4s, #0
	WORD $0x4F000401 // movi v1.4s, #0
	WORD $0x4F000402 // movi v2.4s, #0
	WORD $0x4F000403 // movi v3.4s, #0
	WORD $0x4F000404 // movi v4.4s, #0
	WORD $0x4F000405 // movi v5.4s, #0
	WORD $0x4F000406 // movi v6.4s, #0
	WORD $0x4F000407 // movi v7.4s, #0
	WORD $0x4F000408 // movi v8.4s, #0
	WORD $0x4F000409 // movi v9.4s, #0
	WORD $0x4F00040A // movi v10.4s, #0
	WORD $0x4F00040B // movi v11.4s, #0
	WORD $0x4F00040C // movi v12.4s, #0
	WORD $0x4F00040D // movi v13.4s, #0
	WORD $0x4F00040E // movi v14.4s, #0
	WORD $0x4F00040F // movi v15.4s, #0
	WORD $0x4F000410 // movi v16.4s, #0
	WORD $0x4F000411 // movi v17.4s, #0
	WORD $0x4F000412 // movi v18.4s, #0
	WORD $0x4F000413 // movi v19.4s, #0
	WORD $0x4F000414 // movi v20.4s, #0
	WORD $0x4F000415 // movi v21.4s, #0
	WORD $0x4F000416 // movi v22.4s, #0
	WORD $0x4F000417 // movi v23.4s, #0
	MOVD R2, R6 // block base
	MOVD $0, R7 // ci within block
pwloop:
	CBZ R4, pwdone
	VLD1.P 64(R3), [V24.S4, V25.S4, V26.S4, V27.S4] // w pair (16 f32)
	ADD R7<<2, R6, R8 // &x[block][0][ci]
	WORD $0x4D40C91C // ld1r v28 = x[p0][ci]
	ADD $32, R8, R8
	WORD $0x4E3CCF00 // fmla v0 += v24*v28
	WORD $0x4E3CCF21 // fmla v1 += v25*v28
	WORD $0x4E3CCF42 // fmla v2 += v26*v28
	WORD $0x4E3CCF63 // fmla v3 += v27*v28
	WORD $0x4D40C91C // ld1r v28 = x[p1][ci]
	ADD $32, R8, R8
	WORD $0x4E3CCF04 // fmla v4 += v24*v28
	WORD $0x4E3CCF25 // fmla v5 += v25*v28
	WORD $0x4E3CCF46 // fmla v6 += v26*v28
	WORD $0x4E3CCF67 // fmla v7 += v27*v28
	WORD $0x4D40C91C // ld1r v28 = x[p2][ci]
	ADD $32, R8, R8
	WORD $0x4E3CCF08 // fmla v8 += v24*v28
	WORD $0x4E3CCF29 // fmla v9 += v25*v28
	WORD $0x4E3CCF4A // fmla v10 += v26*v28
	WORD $0x4E3CCF6B // fmla v11 += v27*v28
	WORD $0x4D40C91C // ld1r v28 = x[p3][ci]
	ADD $32, R8, R8
	WORD $0x4E3CCF0C // fmla v12 += v24*v28
	WORD $0x4E3CCF2D // fmla v13 += v25*v28
	WORD $0x4E3CCF4E // fmla v14 += v26*v28
	WORD $0x4E3CCF6F // fmla v15 += v27*v28
	WORD $0x4D40C91C // ld1r v28 = x[p4][ci]
	ADD $32, R8, R8
	WORD $0x4E3CCF10 // fmla v16 += v24*v28
	WORD $0x4E3CCF31 // fmla v17 += v25*v28
	WORD $0x4E3CCF52 // fmla v18 += v26*v28
	WORD $0x4E3CCF73 // fmla v19 += v27*v28
	WORD $0x4D40C91C // ld1r v28 = x[p5][ci]
	WORD $0x4E3CCF14 // fmla v20 += v24*v28
	WORD $0x4E3CCF35 // fmla v21 += v25*v28
	WORD $0x4E3CCF56 // fmla v22 += v26*v28
	WORD $0x4E3CCF77 // fmla v23 += v27*v28
	ADD $1, R7, R7
	CMP $8, R7
	BLT pwnext
	MOVD $0, R7
	ADD R5, R6, R6
pwnext:
	SUB $1, R4, R4
	B pwloop
pwdone:
	VST1.P [V0.S4, V1.S4], 32(R0)
	VST1.P [V2.S4, V3.S4], 32(R1)
	VST1.P [V4.S4, V5.S4], 32(R0)
	VST1.P [V6.S4, V7.S4], 32(R1)
	VST1.P [V8.S4, V9.S4], 32(R0)
	VST1.P [V10.S4, V11.S4], 32(R1)
	VST1.P [V12.S4, V13.S4], 32(R0)
	VST1.P [V14.S4, V15.S4], 32(R1)
	VST1.P [V16.S4, V17.S4], 32(R0)
	VST1.P [V18.S4, V19.S4], 32(R1)
	VST1.P [V20.S4, V21.S4], 32(R0)
	VST1.P [V22.S4, V23.S4], 32(R1)
	RET

// func mulblk8_asm(dst, src []float32, n int, s []float32)
TEXT ·mulblk8_asm(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	MOVD s_base+56(FP), R2
	VLD1 (R2), [V30.S4, V31.S4]
loop16:
	CMP $16, R3
	BLT loop8
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x6E3EDC00 // fmul v0,v0,v30
	WORD $0x6E3FDC21 // fmul v1,v1,v31
	WORD $0x6E3EDC42 // fmul v2,v2,v30
	WORD $0x6E3FDC63 // fmul v3,v3,v31
	VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
	SUB $16, R3
	B loop16
loop8:
	CMP $8, R3
	BLT done
	VLD1.P 32(R1), [V0.S4, V1.S4]
	WORD $0x6E3EDC00 // fmul v0,v0,v30
	WORD $0x6E3FDC21 // fmul v1,v1,v31
	VST1.P [V0.S4, V1.S4], 32(R0)
	SUB $8, R3
	B loop8
done:
	RET

// func sumblk8_asm(dst, src []float32, n int)
TEXT ·sumblk8_asm(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R3
	WORD $0x4F00041A // movi v26.4s, #0
	WORD $0x4F00041B // movi v27.4s, #0
	WORD $0x4F00041C // movi v28.4s, #0
	WORD $0x4F00041D // movi v29.4s, #0
loop16:
	CMP $16, R3
	BLT loop8
	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	WORD $0x4E20D75A // fadd v26+=v0
	WORD $0x4E21D77B // fadd v27+=v1
	WORD $0x4E22D79C // fadd v28+=v2
	WORD $0x4E23D7BD // fadd v29+=v3
	SUB $16, R3
	B loop16
loop8:
	CMP $8, R3
	BLT done
	VLD1.P 32(R1), [V0.S4, V1.S4]
	WORD $0x4E20D75A // fadd v26+=v0
	WORD $0x4E21D77B // fadd v27+=v1
	SUB $8, R3
	B loop8
done:
	WORD $0x4E3CD75A // fadd v26+=v28
	WORD $0x4E3DD77B // fadd v27+=v29
	VST1 [V26.S4, V27.S4], (R0)
	RET

// func qdw3x3s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw3x3s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8, V13.H8]
qdw3x3s1_loop:
	CMP $8, R3
	BLT qdw3x3s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2040 // smlal  v0 += v2.lo * w3
	WORD $0x4F7C2041 // smlal2 v1 += v2.hi * w3
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2840 // smlal  v0 += v2.lo * w4
	WORD $0x4F4C2841 // smlal2 v1 += v2.hi * w4
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2840 // smlal  v0 += v2.lo * w5
	WORD $0x4F5C2841 // smlal2 v1 += v2.hi * w5
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2840 // smlal  v0 += v2.lo * w6
	WORD $0x4F6C2841 // smlal2 v1 += v2.hi * w6
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2840 // smlal  v0 += v2.lo * w7
	WORD $0x4F7C2841 // smlal2 v1 += v2.hi * w7
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2040 // smlal  v0 += v2.lo * w8
	WORD $0x4F4D2041 // smlal2 v1 += v2.hi * w8
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw3x3s1_loop
qdw3x3s1_done:
	RET

// func qdw5x5s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw5x5s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8, V13.H8, V14.H8, V15.H8]
qdw5x5s1_loop:
	CMP $8, R3
	BLT qdw5x5s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2040 // smlal  v0 += v2.lo * w3
	WORD $0x4F7C2041 // smlal2 v1 += v2.hi * w3
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2840 // smlal  v0 += v2.lo * w4
	WORD $0x4F4C2841 // smlal2 v1 += v2.hi * w4
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2840 // smlal  v0 += v2.lo * w5
	WORD $0x4F5C2841 // smlal2 v1 += v2.hi * w5
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2840 // smlal  v0 += v2.lo * w6
	WORD $0x4F6C2841 // smlal2 v1 += v2.hi * w6
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2840 // smlal  v0 += v2.lo * w7
	WORD $0x4F7C2841 // smlal2 v1 += v2.hi * w7
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2040 // smlal  v0 += v2.lo * w8
	WORD $0x4F4D2041 // smlal2 v1 += v2.hi * w8
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5D2040 // smlal  v0 += v2.lo * w9
	WORD $0x4F5D2041 // smlal2 v1 += v2.hi * w9
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6D2040 // smlal  v0 += v2.lo * w10
	WORD $0x4F6D2041 // smlal2 v1 += v2.hi * w10
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7D2040 // smlal  v0 += v2.lo * w11
	WORD $0x4F7D2041 // smlal2 v1 += v2.hi * w11
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2840 // smlal  v0 += v2.lo * w12
	WORD $0x4F4D2841 // smlal2 v1 += v2.hi * w12
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5D2840 // smlal  v0 += v2.lo * w13
	WORD $0x4F5D2841 // smlal2 v1 += v2.hi * w13
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6D2840 // smlal  v0 += v2.lo * w14
	WORD $0x4F6D2841 // smlal2 v1 += v2.hi * w14
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7D2840 // smlal  v0 += v2.lo * w15
	WORD $0x4F7D2841 // smlal2 v1 += v2.hi * w15
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4E2040 // smlal  v0 += v2.lo * w16
	WORD $0x4F4E2041 // smlal2 v1 += v2.hi * w16
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5E2040 // smlal  v0 += v2.lo * w17
	WORD $0x4F5E2041 // smlal2 v1 += v2.hi * w17
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6E2040 // smlal  v0 += v2.lo * w18
	WORD $0x4F6E2041 // smlal2 v1 += v2.hi * w18
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7E2040 // smlal  v0 += v2.lo * w19
	WORD $0x4F7E2041 // smlal2 v1 += v2.hi * w19
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4E2840 // smlal  v0 += v2.lo * w20
	WORD $0x4F4E2841 // smlal2 v1 += v2.hi * w20
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5E2840 // smlal  v0 += v2.lo * w21
	WORD $0x4F5E2841 // smlal2 v1 += v2.hi * w21
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6E2840 // smlal  v0 += v2.lo * w22
	WORD $0x4F6E2841 // smlal2 v1 += v2.hi * w22
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7E2840 // smlal  v0 += v2.lo * w23
	WORD $0x4F7E2841 // smlal2 v1 += v2.hi * w23
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4F2040 // smlal  v0 += v2.lo * w24
	WORD $0x4F4F2041 // smlal2 v1 += v2.hi * w24
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw5x5s1_loop
qdw5x5s1_done:
	RET

// func qdw3x2s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw3x2s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8]
qdw3x2s1_loop:
	CMP $8, R3
	BLT qdw3x2s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2040 // smlal  v0 += v2.lo * w3
	WORD $0x4F7C2041 // smlal2 v1 += v2.hi * w3
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2840 // smlal  v0 += v2.lo * w4
	WORD $0x4F4C2841 // smlal2 v1 += v2.hi * w4
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2840 // smlal  v0 += v2.lo * w5
	WORD $0x4F5C2841 // smlal2 v1 += v2.hi * w5
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw3x2s1_loop
qdw3x2s1_done:
	RET

// func qdw3x1s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw3x1s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8]
qdw3x1s1_loop:
	CMP $8, R3
	BLT qdw3x1s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw3x1s1_loop
qdw3x1s1_done:
	RET

// func qdw5x3s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw5x3s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8, V13.H8]
qdw5x3s1_loop:
	CMP $8, R3
	BLT qdw5x3s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2040 // smlal  v0 += v2.lo * w3
	WORD $0x4F7C2041 // smlal2 v1 += v2.hi * w3
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2840 // smlal  v0 += v2.lo * w4
	WORD $0x4F4C2841 // smlal2 v1 += v2.hi * w4
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2840 // smlal  v0 += v2.lo * w5
	WORD $0x4F5C2841 // smlal2 v1 += v2.hi * w5
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2840 // smlal  v0 += v2.lo * w6
	WORD $0x4F6C2841 // smlal2 v1 += v2.hi * w6
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2840 // smlal  v0 += v2.lo * w7
	WORD $0x4F7C2841 // smlal2 v1 += v2.hi * w7
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2040 // smlal  v0 += v2.lo * w8
	WORD $0x4F4D2041 // smlal2 v1 += v2.hi * w8
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5D2040 // smlal  v0 += v2.lo * w9
	WORD $0x4F5D2041 // smlal2 v1 += v2.hi * w9
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6D2040 // smlal  v0 += v2.lo * w10
	WORD $0x4F6D2041 // smlal2 v1 += v2.hi * w10
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7D2040 // smlal  v0 += v2.lo * w11
	WORD $0x4F7D2041 // smlal2 v1 += v2.hi * w11
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2840 // smlal  v0 += v2.lo * w12
	WORD $0x4F4D2841 // smlal2 v1 += v2.hi * w12
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5D2840 // smlal  v0 += v2.lo * w13
	WORD $0x4F5D2841 // smlal2 v1 += v2.hi * w13
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6D2840 // smlal  v0 += v2.lo * w14
	WORD $0x4F6D2841 // smlal2 v1 += v2.hi * w14
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw5x3s1_loop
qdw5x3s1_done:
	RET

// func qdw5x2s1_asm(acc []int32, src, wp []int16, ncols, W int)
TEXT ·qdw5x2s1_asm(SB), NOSPLIT, $0-88
	MOVD acc_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD wp_base+48(FP), R2
	MOVD ncols+72(FP), R3
	MOVD W+80(FP), R4
	LSL $1, R4, R4 // row stride in bytes (s16)
	VLD1 (R2), [V12.H8, V13.H8]
qdw5x2s1_loop:
	CMP $8, R3
	BLT qdw5x2s1_done
	VLD1 (R0), [V0.S4, V1.S4] // acc[c..c+8)
	MOVD R1, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2040 // smlal  v0 += v2.lo * w0
	WORD $0x4F4C2041 // smlal2 v1 += v2.hi * w0
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2040 // smlal  v0 += v2.lo * w1
	WORD $0x4F5C2041 // smlal2 v1 += v2.hi * w1
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2040 // smlal  v0 += v2.lo * w2
	WORD $0x4F6C2041 // smlal2 v1 += v2.hi * w2
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2040 // smlal  v0 += v2.lo * w3
	WORD $0x4F7C2041 // smlal2 v1 += v2.hi * w3
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4C2840 // smlal  v0 += v2.lo * w4
	WORD $0x4F4C2841 // smlal2 v1 += v2.hi * w4
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5C2840 // smlal  v0 += v2.lo * w5
	WORD $0x4F5C2841 // smlal2 v1 += v2.hi * w5
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F6C2840 // smlal  v0 += v2.lo * w6
	WORD $0x4F6C2841 // smlal2 v1 += v2.hi * w6
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F7C2840 // smlal  v0 += v2.lo * w7
	WORD $0x4F7C2841 // smlal2 v1 += v2.hi * w7
	ADD R4, R5, R5
	MOVD R5, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F4D2040 // smlal  v0 += v2.lo * w8
	WORD $0x4F4D2041 // smlal2 v1 += v2.hi * w8
	ADD $2, R6, R6
	VLD1 (R6), [V2.H8]
	WORD $0x0F5D2040 // smlal  v0 += v2.lo * w9
	WORD $0x4F5D2041 // smlal2 v1 += v2.hi * w9
	VST1.P [V0.S4, V1.S4], 32(R0)
	ADD $16, R1, R1
	SUB $8, R3, R3
	B qdw5x2s1_loop
qdw5x2s1_done:
	RET

